[package]
name = "flowwake-studio"
version = "0.1.5"
description = "OpenFAST & TurbSim desktop workflow environment"
authors = ["Nur M. M. Kalimullah"]
edition = "2021"

[lib]
name = "nurja_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri              = { version = "2.0", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0"
window-vibrancy    = "0.5"
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1.0"
tauri-plugin-global-shortcut = "2.0"
tauri-plugin-dialog = "2.0"
tokio              = { version = "1", features = ["rt"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

tauri-plugin-window-state = "2.0"
