import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open as openDialog } from "@tauri-apps/plugin-dialog";
import { Cloud, FolderOpen, RefreshCw, Eye, Save, ChevronDown } from "lucide-react";
import InfoPopover from "../InfoPopover";
import RawFileModal from "../RawFileModal";
import s from "./InflowWindPanel.module.css";

const ACCENT = "#378ADD";

// ── Field info ────────────────────────────────────────────────────────────────
const INFO = {
  WindType: {
    param: "WindType",
    desc:  "Selects the wind input model. Type 3 (TurbSim BTS) is the standard choice when driving OpenFAST with stochastic IEC wind fields generated by TurbSim.",
    range: "1–7",
    default: "3",
  },
  PropagationDir: {
    param: "PropagationDir",
    desc:  "Direction the wind is travelling, using meteorological convention: 0° = wind blowing from North, 90° = wind blowing from East.",
    range: "−180° to 180°",
    default: "0°",
    unit: "degrees",
  },
  VFlowAng: {
    param: "VFlowAng",
    desc:  "Vertical inclination of the mean flow. Positive = upslope flow. Typically 0° for flat terrain; may be non-zero for complex terrain studies.",
    range: "−45° to 45°",
    default: "0°",
    unit: "degrees",
  },
  WindVziList: {
    param: "WindVziList",
    desc:  "Height at which InflowWind writes out point wind velocity to the OpenFAST output file. Should match HubHt in ElastoDyn so hub-height wind speed appears in results.",
    unit: "m",
    note: "Tip: set this equal to the ElastoDyn HubHt parameter.",
  },
  HWindSpeed: {
    param: "HWindSpeed",
    desc:  "Mean horizontal wind speed at the reference height. Used only for WindType=1 (Steady). AeroDyn will see this speed at every grid point.",
    unit: "m/s",
    default: "12.0",
  },
  RefHt: {
    param: "RefHt",
    desc:  "Height at which HWindSpeed is defined. The power law profile U(z) = HWindSpeed × (z/RefHt)^PLexp is applied above and below this height.",
    unit: "m",
    default: "hub height",
  },
  PLexp: {
    param: "PLexp",
    desc:  "Wind shear exponent α in the power law profile U(z) ∝ z^α. IEC 61400-1 default is 0.2 for land-based turbines; offshore typically 0.14.",
    range: "0.05–0.40",
    default: "0.2",
    note: "IEC 61400-1 Ed.3 §6.3 specifies α = 0.2 unless site-specific data is available.",
  },
  FileName_BTS: {
    param: "FileName_BTS",
    desc:  "Path to the TurbSim binary full-field wind file (.bts). Must match the grid dimensions (HubHt, GridHeight, GridWidth) used in the OpenFAST model.",
    note:  "Use 'Scan project' to auto-discover .bts files generated by TurbSim or DLC Batch.",
  },
  SumPrint: {
    param: "SumPrint",
    desc:  "When True, InflowWind writes a <RootName>.IfW.sum summary file with mean wind speed, turbulence intensity, and power spectral density at the output point.",
    default: "False",
  },
  Filename_Uni: {
    param: "Filename_Uni",
    desc:  "Path to the Uniform wind time-series file (.wnd). Each row contains: Time, HorSpd, WindDir, VertSpd, HorShr, VerShr, LnVShr, GstSpd.",
    note:  "Uniform wind files can be created manually or with the InflowWind pre-processor.",
  },
  RefHt_Uni: {
    param: "RefHt_Uni",
    desc:  "Height at which HorSpd in the .wnd file is defined. Wind profile shear is applied relative to this height.",
    unit:  "m",
  },
  RefLength: {
    param: "RefLength",
    desc:  "Reference length used to non-dimensionalise the horizontal and vertical shear columns in the Uniform wind file.",
    unit:  "m",
  },
};

// ── Wind types (HAWC2 / type 5 omitted — niche, complex, not yet supported) ──
const WIND_TYPES = [
  { value: 1, label: "Steady",      desc: "Constant mean speed + power law shear" },
  { value: 3, label: "TurbSim BTS", desc: "Binary full-field wind file from TurbSim (.bts)" },
  { value: 2, label: "Uniform",     desc: "Time-varying uniform wind from .wnd file" },
];

// ── Auto-name helper ──────────────────────────────────────────────────────────
function autoFilename(windType, p) {
  if (windType === 1) {
    const v = String(Number(p.HWindSpeed).toFixed(1)).replace(".", "p");
    return `IFW_Steady_V${v}.dat`;
  }
  if (windType === 2 && p.Filename_Uni.trim() && p.Filename_Uni !== "none") {
    const base = p.Filename_Uni.trim().split(/[\\/]/).pop().replace(/\.wnd$/i, "");
    return `IFW_Uni_${base}.dat`;
  }
  if (windType === 3 && p.FileName_BTS.trim()) {
    const base = p.FileName_BTS.trim().split(/[\\/]/).pop().replace(/\.bts$/i, "");
    return `IFW_${base}.dat`;
  }
  return "InflowWind.dat";
}

// ── Default parameters ────────────────────────────────────────────────────────
const DEFAULT = {
  WindType:       3,
  PropagationDir: 0.0,
  VFlowAng:       0.0,
  NWindVel:       1,
  WindVxiList:    0.0,
  WindVyiList:    0.0,
  WindVziList:    90.0,
  HWindSpeed:     12.0,
  RefHt:          90.0,
  PLexp:          0.2,
  FileName_BTS:   "",
  Filename_Uni:   "none",
  RefHt_Uni:      90.0,
  RefLength:      126.0,
  SumPrint:       false,
};

// ── Parser ────────────────────────────────────────────────────────────────────
function parseInflowWindFile(content) {
  const kv = {};
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    // Skip pure comment / separator / section-header lines
    if (line.startsWith("!") || line.startsWith("=") || /^-{3,}/.test(line)) continue;

    let rest = line;
    let value;

    // Quoted string value
    if (rest.startsWith('"')) {
      const end = rest.indexOf('"', 1);
      if (end === -1) continue;
      value = rest.slice(0, end + 1);
      rest  = rest.slice(end + 1).trim();
    } else {
      // Unquoted: grab up to first whitespace or comma
      const sp = rest.search(/[\s,]/);
      if (sp === -1) continue;
      value = rest.slice(0, sp);
      rest  = rest.slice(sp).trim();
    }

    // Key = next alpha token
    const m = rest.match(/^([A-Za-z_][A-Za-z0-9_]*)/);
    if (!m) continue;
    kv[m[1]] = value;
  }
  return kv;
}

function parsedToState(kv) {
  const bool = (k, d) => (k in kv ? kv[k].toLowerCase() === "true" : d);
  const num  = (k, d) => { if (!(k in kv)) return d; const v = parseFloat(kv[k]); return isNaN(v) ? d : v; };
  const str  = (k, d) => (k in kv ? kv[k].replace(/^"|"$/g, "") : d);

  return {
    ...DEFAULT,
    WindType:       num("WindType",       DEFAULT.WindType),
    PropagationDir: num("PropagationDir", DEFAULT.PropagationDir),
    VFlowAng:       num("VFlowAng",       DEFAULT.VFlowAng),
    NWindVel:       num("NWindVel",       DEFAULT.NWindVel),
    WindVxiList:    num("WindVxiList",    DEFAULT.WindVxiList),
    WindVyiList:    num("WindVyiList",    DEFAULT.WindVyiList),
    WindVziList:    num("WindVziList",    DEFAULT.WindVziList),
    HWindSpeed:     num("HWindSpeed",     DEFAULT.HWindSpeed),
    RefHt:          num("RefHt",          DEFAULT.RefHt),
    PLexp:          num("PLexp",          DEFAULT.PLexp),
    FileName_BTS:   str("FileName_BTS",   DEFAULT.FileName_BTS),
    Filename_Uni:   str("Filename_Uni",   DEFAULT.Filename_Uni),
    RefHt_Uni:      num("RefHt_Uni",      DEFAULT.RefHt_Uni),
    RefLength:      num("RefLength",      DEFAULT.RefLength),
    SumPrint:       bool("SumPrint",      DEFAULT.SumPrint),
    __rawKV__: kv,
  };
}

// ── Builder ───────────────────────────────────────────────────────────────────
function buildInflowWindContent(p) {
  const b   = v  => (v ? "True" : "False");
  const r   = v  => { const n = Number(v); return isNaN(n) ? String(v) : String(n); };
  const pad = sv => String(sv).padEnd(14);
  const q   = v  => `"${v}"`;

  const WRITTEN = new Set([
    "WindType","PropagationDir","VFlowAng","VelInterpCubic",
    "NWindVel","WindVxiList","WindVyiList","WindVziList",
    "HWindSpeed","RefHt","PLexp",
    "Filename_Uni","RefHt_Uni","RefLength",
    "FileName_BTS",
    "SumPrint","Echo",
  ]);
  const rawKV = p.__rawKV__ || {};
  const passThrough = Object.entries(rawKV)
    .filter(([k]) => !WRITTEN.has(k) && !k.startsWith("__"))
    .map(([k, v]) => `${String(v).padEnd(14)} ${k}`);

  const lines = [
    `------- InflowWind v3.01.* INPUT FILE ----------------------------------------`,
    `InflowWind input file generated by FlowWake Studio`,
    `------- SIMULATION CONTROL ---------------------------------------------------`,
    `${pad(b(false))} Echo            - Echo input data to <RootName>.IfW.echo (flag)`,
    `${pad(r(p.WindType))} WindType        - Wind model {1=Steady;2=Uniform;3=TurbSim BTS;4=Bladed;5=HAWC2;6=User DLL;7=User File} (-)`,
    `${pad(r(p.PropagationDir))} PropagationDir  - Wind propagation direction — meteorological convention (degrees)`,
    `${pad(r(p.VFlowAng))} VFlowAng        - Upflow angle (degrees, about y-axis)`,
    `${pad(b(false))} VelInterpCubic  - Cubic temporal interpolation (flag)`,
    `${pad(r(p.NWindVel))} NWindVel        - Number of wind velocity output points [0–9] (-)`,
    `${pad(r(p.WindVxiList))} WindVxiList     - X-coordinates for wind velocity output (m)`,
    `${pad(r(p.WindVyiList))} WindVyiList     - Y-coordinates for wind velocity output (m)`,
    `${pad(r(p.WindVziList))} WindVziList     - Z-coordinates for wind velocity output (m)`,
    `================== Parameters for Steady Wind [WindType=1] ====================`,
    `${pad(r(p.HWindSpeed))} HWindSpeed      - Horizontal wind speed (m/s)`,
    `${pad(r(p.RefHt))} RefHt           - Reference height for wind speed (m)`,
    `${pad(r(p.PLexp))} PLexp           - Power law exponent (-)`,
    `================== Parameters for Uniform Wind [WindType=2] ===================`,
    `${pad(q(p.Filename_Uni))} Filename_Uni    - Uniform wind file (.wnd)`,
    `${pad(r(p.RefHt_Uni))} RefHt_Uni       - Reference height for uniform wind (m)`,
    `${pad(r(p.RefLength))} RefLength       - Reference length for shear (m)`,
    `================== Parameters for Binary TurbSim FF [WindType=3] ==============`,
    `${pad(q(p.FileName_BTS))} FileName_BTS    - TurbSim binary wind field file (.bts)`,
    `================== Parameters for Binary Bladed-style FF [WindType=4] =========`,
    `${pad(q("none"))} FilenameRoot    - Root name of Bladed FF wind file`,
    `${pad(b(false))} TowerFile       - Have tower file (.twr) (flag)`,
    `================== Parameters for HAWC-format binary files [WindType=5] =======`,
    `${pad(q("none"))} FileName_u      - u-component wind file (.bin)`,
    `${pad(q("none"))} FileName_v      - v-component wind file (.bin)`,
    `${pad(q("none"))} FileName_w      - w-component wind file (.bin)`,
    `${pad("64")} nx              - grids in x (-)`,
    `${pad("32")} ny              - grids in y (-)`,
    `${pad("32")} nz              - grids in z (-)`,
    `${pad("25")} dx              - x grid spacing (m)`,
    `${pad("2")} dy              - y grid spacing (m)`,
    `${pad("2")} dz              - z grid spacing (m)`,
    `${pad(r(p.WindVziList))} RefHt_Hawc      - HAWC reference height (m)`,
    `${pad("1")} ScaleMethod     - Turbulence scaling method (-)`,
    `${pad("1")} SFx             - x scaling factor (-)`,
    `${pad("1")} SFy             - y scaling factor (-)`,
    `${pad("1")} SFz             - z scaling factor (-)`,
    `${pad("12")} SigmaFx         - x turbulence std dev target (m/s)`,
    `${pad("8")} SigmaFy         - y turbulence std dev target (m/s)`,
    `${pad("2")} SigmaFz         - z turbulence std dev target (m/s)`,
    `${pad(r(p.HWindSpeed))} URef            - Mean u-component at reference height (m/s)`,
    `${pad("1")} WindProfile     - Wind profile type (0=const; 1=log; 2=power law) (-)`,
    `${pad(r(p.PLexp))} PLExp_Hawc      - Power law exponent for HAWC (-)`,
    `${pad("0.01")} Z0              - Surface roughness length (m)`,
    `${pad("0")} XOffset         - Initial x offset (m)`,
    `================== LIDAR Parameters ==========================================`,
    `${pad("0")} SensorType      - Lidar sensor type (0=None) (-)`,
    `${pad("0")} NumPulseGate    - Lidar measurement gates (-)`,
    `${pad("1")} MeasurementInterval - Time between measurements (s)`,
    `${pad(b(false))} ConsiderHubMotion - Consider hub motion impact on lidar (flag)`,
    `================== OUTPUT ====================================================`,
    `${pad(b(p.SumPrint))} SumPrint        - Print summary to <RootName>.IfW.sum (flag)`,
    `              OutList         - Output channels`,
    `"Wind1VelX"`,
    `"Wind1VelY"`,
    `"Wind1VelZ"`,
    `END of input file (the word "END" must appear in the first 3 columns of this last OutList line)`,
    `---------------------------------------------------------------------------------------`,
  ];

  if (passThrough.length) {
    lines.push(
      "!--- Parameters not editable in this UI (preserved verbatim from original file) ---",
      ...passThrough,
    );
  }

  return lines.join("\n");
}

// ── Patch writer ──────────────────────────────────────────────────────────────
// Used when SAVING an existing file.
// Walks the original content line-by-line; for every line whose key is in our
// VALUE_MAP it replaces only the value token, leaving everything else byte-for-byte
// identical (LIDAR params, HAWC2 section, comments, whitespace, section order).
// Each key is patched at most once (first occurrence) — safe when the same
// parameter name reappears in a different section (e.g. RefHt in HAWC2).
function patchInflowWindContent(originalContent, p) {
  const b = v => (v ? "True" : "False");
  const r = v => { const n = Number(v); return isNaN(n) ? String(v) : String(n); };
  const q = v => `"${v}"`;

  // Map of key → new formatted value (only the keys we actually expose in the UI)
  const VALUE_MAP = {
    WindType:       r(p.WindType),
    PropagationDir: r(p.PropagationDir),
    VFlowAng:       r(p.VFlowAng),
    NWindVel:       r(p.NWindVel),
    WindVxiList:    r(p.WindVxiList),
    WindVyiList:    r(p.WindVyiList),
    WindVziList:    r(p.WindVziList),
    HWindSpeed:     r(p.HWindSpeed),
    RefHt:          r(p.RefHt),
    PLexp:          r(p.PLexp),
    FileName_BTS:   q(p.FileName_BTS),
    Filename_Uni:   q(p.Filename_Uni),
    RefHt_Uni:      r(p.RefHt_Uni),
    RefLength:      r(p.RefLength),
    SumPrint:       b(p.SumPrint),
  };

  const alreadyPatched = new Set(); // patch each key at most once

  return originalContent.split("\n").map(rawLine => {
    const trimmed = rawLine.trim();
    // Skip blanks, comments, separator lines, section headers
    if (!trimmed
      || trimmed.startsWith("!")
      || trimmed.startsWith("=")
      || /^-{3,}/.test(trimmed)) return rawLine;

    // ── Extract the value token and what follows it ───────────────────────
    let origValueToken, afterValue;
    if (trimmed.startsWith('"')) {
      const end = trimmed.indexOf('"', 1);
      if (end === -1) return rawLine;
      origValueToken = trimmed.slice(0, end + 1);
      afterValue     = trimmed.slice(end + 1);
    } else {
      const sp = trimmed.search(/\s/);
      if (sp === -1) return rawLine;
      origValueToken = trimmed.slice(0, sp);
      afterValue     = trimmed.slice(sp);
    }

    // ── Extract the key (first alpha token after the value) ───────────────
    const keyMatch = afterValue.trimStart().match(/^([A-Za-z_][A-Za-z0-9_]*)/);
    if (!keyMatch) return rawLine;
    const key = keyMatch[1];

    if (!(key in VALUE_MAP))     return rawLine; // not one of our keys
    if (alreadyPatched.has(key)) return rawLine; // already updated once
    alreadyPatched.add(key);

    // ── Replace value, preserve leading whitespace + everything after ─────
    const newValue   = VALUE_MAP[key];
    const leadingWS  = rawLine.slice(0, rawLine.length - rawLine.trimStart().length);
    // Keep column alignment: pad at least as wide as the original token
    const padWidth   = Math.max(origValueToken.length, String(newValue).length, 14);
    const paddedNew  = String(newValue).padEnd(padWidth);

    return `${leadingWS}${paddedNew}${afterValue}`;
  }).join("\n");
}

// ── Wind visualisation SVG ─────────────────────────────────────────────────────
// Shows a turbine (right) + horizontal shear arrows (left) — longer at top.
// For Steady: lengths follow a rough power-law gradient.
// For BTS: same arrows but slightly irregular to hint at turbulence.
function WindVizSVG({ windType, windSpeed, plExp }) {
  const c = "#378ADD";

  // [svgY, relativeLen] pairs — top to bottom = high altitude to low altitude
  const arrowRows = [
    [16, 1.00],
    [29, 0.83],
    [42, 0.67],
    [55, 0.52],
    [68, 0.39],
  ];
  const MAX_LEN = 24;

  return (
    <svg viewBox="0 0 100 110" width="100%" height="180" style={{ display: "block" }}>
      {/* Tower */}
      <line x1="68" y1="54" x2="68" y2="100"
        style={{ stroke: "var(--tx-4)" }} strokeWidth="5" strokeLinecap="round"/>
      {/* Base */}
      <line x1="56" y1="101" x2="80" y2="101"
        style={{ stroke: "var(--bd-strong)" }} strokeWidth="2"/>
      {/* Nacelle */}
      <rect x="60" y="48" width="16" height="8" rx="2"
        style={{ fill: "var(--bg-hover-md)" }}/>
      {/* Hub */}
      <circle cx="68" cy="52" r="3.5" fill={c}/>
      {/* Blades — up, lower-left, lower-right */}
      <line x1="68" y1="48" x2="68" y2="14"  stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      <line x1="65" y1="55" x2="42" y2="68"  stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      <line x1="71" y1="55" x2="94" y2="68"  stroke={c} strokeWidth="2.5" strokeLinecap="round"/>

      {/* Shear arrows */}
      {arrowRows.map(([y, rel], i) => {
        const len = MAX_LEN * rel;
        // For BTS: slight vertical wobble to hint at turbulence
        const dy  = windType === 3 ? ((i * 7) % 5) - 2 : 0;
        return (
          <g key={y} opacity="0.62">
            <line x1="4" y1={y + dy} x2={4 + len} y2={y + dy}
              stroke={c} strokeWidth="1.4" strokeLinecap="round"/>
            <polyline
              points={`${4 + len - 5},${y + dy - 3.5} ${4 + len},${y + dy} ${4 + len - 5},${y + dy + 3.5}`}
              stroke={c} strokeWidth="1.4" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
          </g>
        );
      })}

      {/* Module label */}
      <text x="4" y="108" fontSize="6"
        style={{ fill: c }} fontFamily="-apple-system,sans-serif" opacity="0.7">
        {windType === 1
          ? `Steady  ${Number(windSpeed || 0).toFixed(1)} m/s  α=${plExp}`
          : windType === 2
          ? "Uniform (.wnd)"
          : windType === 3
          ? "TurbSim BTS"
          : "InflowWind"}
      </text>
    </svg>
  );
}

// ── Toggle ────────────────────────────────────────────────────────────────────
function Toggle({ value, onChange, label }) {
  return (
    <div className={s.toggleRow}>
      <button
        type="button"
        className={`${s.toggle} ${value ? s.on : ""}`}
        onClick={() => onChange(!value)}
      >
        <span className={s.toggleThumb} />
      </button>
      {label && <span className={s.toggleLabel}>{label}</span>}
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────
export default function InflowWindPanel({
  onLog, project,
  filePathFromProject, reloadKey, onDirtyChange, onRegisterSave,
  onWindParamsChange,
  simRunning = false,
}) {
  const [p,             _setP]          = useState(DEFAULT);
  const [filePath,      setFilePath]    = useState("");
  const [isDirtyFlag,   setIsDirtyFlag] = useState(false);
  const [btsFiles,      setBtsFiles]    = useState([]);
  const [scanning,      setScanning]    = useState(false);
  const [showRaw,       setShowRaw]     = useState(false);
  const [rawContent,    setRawContent]  = useState("");
  const [generating,    setGenerating]  = useState(false);
  const [customDatName, setCustomDatName] = useState("");

  // Ref holds JSON snapshot of last saved/loaded state — written synchronously
  // to avoid React batching race between setP and the snapshot update.
  const originalRef = useRef(null);

  // Ref holds the raw file text of the currently loaded file.
  // handleSave uses patchInflowWindContent() on this to update only the known
  // keys while leaving every other line (LIDAR, HAWC2, Bladed…) untouched.
  // handleGenerate stores the freshly created template here so subsequent saves
  // also use the patch strategy from that point on.
  const originalContentRef = useRef("");

  // Wrapped setP — marks panel dirty on every user-driven change
  const setP = useCallback((updater) => {
    _setP(updater);
    setIsDirtyFlag(true);
  }, []);

  // isDirty: file open + user touched something + state diverged from snapshot
  const isDirty = !!filePath && isDirtyFlag &&
    originalRef.current !== null && JSON.stringify(p) !== originalRef.current;

  // Revert detection: clear dirty flag if user undid all their changes
  useEffect(() => {
    if (!isDirtyFlag || originalRef.current === null) return;
    if (JSON.stringify(p) === originalRef.current) setIsDirtyFlag(false);
  }, [p, isDirtyFlag]); // eslint-disable-line react-hooks/exhaustive-deps

  const set    = key => e => setP(prev => ({ ...prev, [key]: e.target.value }));
  // Numbers must be stored as Number (not string) so JSON.stringify comparison
  // works correctly for the revert-detection / isDirty logic.
  const setNum = key => e => setP(prev => ({ ...prev, [key]: Number(e.target.value) }));

  const autoName         = useMemo(() => autoFilename(p.WindType, p), [p.WindType, p.HWindSpeed, p.FileName_BTS, p.Filename_Uni]); // eslint-disable-line react-hooks/exhaustive-deps
  const effectiveDatName = customDatName.trim() || autoName;

  // ── File operations ────────────────────────────────────────────────────────

  const loadFile = async (path) => {
    try {
      const content  = await invoke("read_text_file", { path });
      const kv       = parseInflowWindFile(content);
      const newState = parsedToState(kv);
      originalContentRef.current = content;          // raw text for patch writes
      originalRef.current = JSON.stringify(newState); // JSON snapshot for dirty detection
      _setP(newState);
      setIsDirtyFlag(false);
      onLog?.("ok", `Loaded ${path.split("/").pop()}`);
    } catch {
      // File is missing — auto-generate it from defaults so that subsequent
      // patchInputFileKey calls from the OpenFAST run card have a valid file
      // to read-and-patch (on Windows the file often doesn't exist until it is
      // explicitly saved, which caused the one-way sync problem).
      const fallback = { ...DEFAULT };
      const content  = buildInflowWindContent(fallback);
      try {
        await invoke("write_text_file", { path, content });
        originalContentRef.current = content;
        originalRef.current = JSON.stringify(fallback);
        _setP(fallback);
        onLog?.("info", `${path.split("/").pop()} not found — created with defaults`);
      } catch {
        // Model directory may not exist yet (project not fully configured) — stay silent
      }
    }
  };

  const handleOpen = async () => {
    try {
      const f = await openDialog({
        multiple: false, directory: false,
        filters: [{ name: "InflowWind input", extensions: ["dat"] }],
      });
      if (!f) return;
      setFilePath(f);
      await loadFile(f);
    } catch {}
  };

  const handleSave = useCallback(async () => {
    if (simRunning) {
      onLog?.("warn", "⚠ OpenFAST is running — save blocked to protect the active simulation. Wait for it to finish.");
      return;
    }
    if (!filePath) {
      onLog?.("warn", "No file open — use Open .dat or Generate first.");
      return;
    }
    // Patch strategy: only the UI-known values change; every other line
    // (LIDAR section, HAWC2 section, Bladed section, custom comments…)
    // is left exactly as it was in the file we originally read.
    const content = originalContentRef.current
      ? patchInflowWindContent(originalContentRef.current, p)
      : buildInflowWindContent(p); // fallback for programmatically set paths
    try {
      await invoke("write_text_file", { path: filePath, content });
      originalContentRef.current = content;          // patch from the saved version next time
      originalRef.current = JSON.stringify(p);       // advance dirty snapshot
      setIsDirtyFlag(false);
      onLog?.("ok", `Saved ${filePath.split("/").pop()}`);
    } catch (err) {
      onLog?.("error", `Save failed: ${String(err)}`);
    }
  }, [filePath, p]); // eslint-disable-line react-hooks/exhaustive-deps

  // Generate a new file in the project dir, then treat it as the loaded file
  const handleGenerate = async () => {
    if (!project) { onLog?.("warn", "Open a project directory first."); return; }
    if (p.WindType === 3 && !p.FileName_BTS.trim()) { onLog?.("warn", "Select a .bts file first."); return; }
    setGenerating(true);
    const outPath = `${project.modelDir ?? project.workingDir}/${effectiveDatName}`;
    const content = buildInflowWindContent(p);
    try {
      await invoke("write_text_file", { path: outPath, content });
      // Treat the generated file as the "open" file — store raw content so
      // subsequent saves use the patch strategy (preserving any future manual edits
      // to the file outside this app).
      originalContentRef.current = content;
      originalRef.current = JSON.stringify(p);
      setFilePath(outPath);
      setIsDirtyFlag(false);
      onLog?.("ok", `Generated → ${outPath}`);
    } catch (err) {
      onLog?.("error", `Write failed: ${err.message ?? err}`);
    }
    setGenerating(false);
  };

  const handleViewRaw = async () => {
    if (!filePath) {
      onLog?.("warn", "Load or save the InflowWind file first — then View will show the actual file on disk.");
      return;
    }
    try {
      const content = await invoke("read_text_file", { path: filePath });
      setRawContent(content);
      setShowRaw(true);
    } catch (err) {
      onLog?.("error", `Cannot read file: ${err}`);
    }
  };

  // Cmd+S / Ctrl+S to save
  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "s") { e.preventDefault(); handleSave(); }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [handleSave]);

  // ── Project integration effects ────────────────────────────────────────────
  useEffect(() => {
    if (!filePathFromProject) return;
    setFilePath(filePathFromProject);
    loadFile(filePathFromProject);
  }, [filePathFromProject]); // eslint-disable-line react-hooks/exhaustive-deps

  // Reload from disk when OpenFASTPanel patches the inflowwind file externally
  useEffect(() => {
    if (!reloadKey || !filePathFromProject) return;
    loadFile(filePathFromProject);
  }, [reloadKey]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { onDirtyChange?.(isDirty); }, [isDirty]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { onRegisterSave?.(handleSave); }, [handleSave]); // eslint-disable-line react-hooks/exhaustive-deps

  // Broadcast live wind params to the OpenFAST run panel whenever the user
  // changes WindType, wind speed, or BTS file — no save required.
  useEffect(() => {
    if (!filePath || !onWindParamsChange) return;
    const btsBasename = p.FileName_BTS
      ? p.FileName_BTS.replace(/\\/g, "/").split("/").pop()
      : "";
    onWindParamsChange(p.WindType, String(p.HWindSpeed), btsBasename);
  }, [p.WindType, p.HWindSpeed, p.FileName_BTS]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── BTS scanning ───────────────────────────────────────────────────────────
  const scanBts = useCallback(async () => {
    if (!project) return;
    setScanning(true);
    try {
      const raw = await invoke("sidecar_call", {
        payload: JSON.stringify({ cmd: "list_bts_files", working_dir: project.windDir ?? project.workingDir }),
      });
      const res = JSON.parse(raw);
      if (res.ok) setBtsFiles(res.files);
    } catch {}
    setScanning(false);
  }, [project]);

  useEffect(() => { if (project) scanBts(); }, [project, scanBts]);

  const browseBts = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "TurbSim wind field", extensions: ["bts"] }] });
      if (f) setP(prev => ({ ...prev, FileName_BTS: f }));
    } catch {}
  };

  const browseWnd = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "Uniform wind file", extensions: ["wnd"] }] });
      if (f) setP(prev => ({ ...prev, Filename_Uni: f }));
    } catch {}
  };

  // ── Derived display values ─────────────────────────────────────────────────
  const Lbl = ({ children, k }) => (
    <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
      {children}
      <InfoPopover content={INFO[k]} accentColor={ACCENT} />
    </span>
  );

  const wt = WIND_TYPES.find(t => t.value === p.WindType);

  const displayPath = filePath
    ? filePath.replace(/\\/g, "/").split("/").slice(-3).join("/")
    : "";

  // Sidebar stats — always show Type + Hub Ht; add wind-type-specific cards
  const stats = [
    { k: "Type",       v: wt?.label || "—" },
    { k: "Hub height", v: `${p.WindVziList} m` },
    ...(p.WindType === 1 ? [
      { k: "Wind speed", v: `${Number(p.HWindSpeed).toFixed(1)} m/s` },
      { k: "Ref height", v: `${p.RefHt} m` },
      { k: "Shear α",    v: String(p.PLexp) },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
    ] : p.WindType === 2 ? [
      { k: "Ref height", v: `${p.RefHt_Uni} m` },
      { k: "Ref length", v: `${p.RefLength} m` },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
    ] : [
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
    ]),
  ];

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className={s.panel}>

      {/* ── Header ────────────────────────────────────────────────────────── */}
      <div className={s.header}>
        <Cloud size={14} strokeWidth={1.8} className={s.headerIcon} />
        <span className={s.title}>InflowWind</span>
        <span className={s.subtitle}>inflow conditions</span>
        <span className={s.badge}>v3.01</span>
        <div style={{ flex: 1 }} />
        <button className={`${s.headerBtn} ${s.headerBtnPrimary}`} onClick={handleOpen} type="button">
          <FolderOpen size={12} strokeWidth={1.8} /> Open .dat
        </button>
        <button className={s.eyeBtn} onClick={handleViewRaw} title="Preview .dat content" type="button">
          <Eye size={12} strokeWidth={1.8} />
          View .dat
        </button>
      </div>

      {/* ── File bar — always visible, Save lives here ────────────────────── */}
      <div className={[s.fileBar, filePath ? s.fileBarLoaded : ""].join(" ")}>
        <span className={`${s.filePath} ${filePath ? s.filePathSet : ""}`}>
          {filePath
            ? (displayPath || filePath.split("/").pop())
            : "No file open — click Open .dat to load an existing file"}
        </span>
        <span className={s.dirtyDot} style={{ opacity: isDirty ? 1 : 0 }} title="Unsaved changes" />
        <button
          className={[s.saveBtn, (!isDirty || simRunning) ? s.saveBtnInactive : ""].join(" ")}
          onClick={(!isDirty || simRunning) ? undefined : handleSave}
          type="button"
          title={simRunning ? "OpenFAST is running — save blocked" : "Save (⌘S)"}
        >
          <Save size={11} strokeWidth={2} /> Save
        </button>
      </div>

      {/* ── Simulation running banner ──────────────────────────────────────── */}
      {simRunning && (
        <div style={{
          display: "flex", alignItems: "center", gap: 8,
          padding: "7px 18px",
          background: "rgba(217,119,6,0.10)",
          borderBottom: "0.5px solid rgba(217,119,6,0.28)",
          flexShrink: 0,
        }}>
          <span style={{ fontSize: 13 }}>⚠</span>
          <span style={{ fontSize: 12, fontWeight: 500, color: "#92400E" }}>
            OpenFAST is running — saving is disabled to protect the active simulation
          </span>
        </div>
      )}

      {/* ── Raw file modal ─────────────────────────────────────────────────── */}
      {showRaw && rawContent && (
        <RawFileModal
          content={rawContent}
          filename={filePath ? filePath.split("/").pop() : "InflowWind.dat"}
          fromDisk={!!filePath}
          hasDirtyWarning={isDirty}
          onClose={() => setShowRaw(false)}
        />
      )}

      {/* ── Content row ───────────────────────────────────────────────────── */}
      <div className={s.contentRow}>

        {/* Form area */}
        <div className={s.scroll}>
          <div className={s.form}>

            {/* Wind Source */}
            <p className={s.sectionHead}>
              Wind Source
              <InfoPopover content={INFO.WindType} accentColor={ACCENT} />
            </p>

            <div className={s.typeBar}>
              {WIND_TYPES.map(t => (
                <button
                  key={t.value}
                  type="button"
                  className={`${s.typeBtn} ${p.WindType === t.value ? s.typeBtnActive : ""}`}
                  onClick={() => setP(prev => ({ ...prev, WindType: t.value }))}
                >
                  {t.label}
                </button>
              ))}
            </div>
            <p className={s.typeDesc}>{wt?.desc}</p>

            {/* ── Steady params ──────────────────────────────────────────── */}
            {p.WindType === 1 && (
              <div className={s.grid2} style={{ marginTop: 14 }}>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="HWindSpeed">Wind speed</Lbl></span>
                  <div className={s.inputRow}>
                    <input className={s.inp} type="number" value={p.HWindSpeed} onChange={setNum("HWindSpeed")} step="0.5" />
                    <span className={s.unit}>m/s</span>
                  </div>
                </label>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="RefHt">Reference height</Lbl></span>
                  <div className={s.inputRow}>
                    <input className={s.inp} type="number" value={p.RefHt} onChange={setNum("RefHt")} />
                    <span className={s.unit}>m</span>
                  </div>
                </label>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="PLexp">Power law exponent α</Lbl></span>
                  <input className={s.inp} type="number" value={p.PLexp} onChange={setNum("PLexp")} step="0.01" />
                </label>
              </div>
            )}

            {/* ── Uniform wind params ────────────────────────────────────── */}
            {p.WindType === 2 && (
              <div style={{ marginTop: 14, marginBottom: 22 }}>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="Filename_Uni">Wind file (.wnd)</Lbl></span>
                  <div className={s.fileRow}>
                    <input className={s.inp} type="text" value={p.Filename_Uni === "none" ? "" : p.Filename_Uni}
                      onChange={e => setP(prev => ({ ...prev, Filename_Uni: e.target.value || "none" }))}
                      placeholder="Path to .wnd file…" />
                    <button className={s.browseBtn} onClick={browseWnd} title="Browse" type="button">
                      <FolderOpen size={13} strokeWidth={1.8} />
                    </button>
                  </div>
                </label>
                <div className={s.grid2} style={{ marginTop: 12 }}>
                  <label className={s.field}>
                    <span className={s.fieldLabel}><Lbl k="RefHt_Uni">Reference height</Lbl></span>
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.RefHt_Uni} onChange={setNum("RefHt_Uni")} />
                      <span className={s.unit}>m</span>
                    </div>
                  </label>
                  <label className={s.field}>
                    <span className={s.fieldLabel}><Lbl k="RefLength">Reference length</Lbl></span>
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.RefLength} onChange={setNum("RefLength")} />
                      <span className={s.unit}>m</span>
                    </div>
                  </label>
                </div>
              </div>
            )}

            {/* ── TurbSim BTS params ─────────────────────────────────────── */}
            {p.WindType === 3 && (
              <div style={{ marginTop: 14, marginBottom: 22 }}>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="FileName_BTS">Wind field file (.bts)</Lbl></span>
                  <div className={s.fileRow}>
                    <input className={s.inp} type="text" value={p.FileName_BTS}
                      onChange={set("FileName_BTS")} placeholder="Path to .bts file…" />
                    <button className={s.browseBtn} onClick={browseBts} title="Browse" type="button">
                      <FolderOpen size={13} strokeWidth={1.8} />
                    </button>
                  </div>
                </label>

                {project && (
                  <div className={s.scanRow}>
                    <button className={s.scanBtn} onClick={scanBts} disabled={scanning} type="button">
                      <RefreshCw size={11} strokeWidth={2} className={scanning ? s.spinning : ""} />
                      {scanning ? "Scanning…" : "Scan project"}
                    </button>
                    {btsFiles.length > 0 ? (
                      <div className={s.btsPickerWrap}>
                        <select className={s.btsPicker} value={p.FileName_BTS}
                          onChange={e => e.target.value && setP(prev => ({ ...prev, FileName_BTS: e.target.value }))}>
                          <option value="">— {btsFiles.length} .bts files found —</option>
                          {btsFiles.map(f => (
                            <option key={f.path} value={f.path}>{f.rel}</option>
                          ))}
                        </select>
                        <ChevronDown size={12} className={s.btsChevron} />
                      </div>
                    ) : !scanning && (
                      <span className={s.noBts}>No .bts files — run TurbSim or DLC Batch first</span>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* Flow Direction */}
            <p className={s.sectionHead} style={{ marginTop: p.WindType === 1 ? 0 : 4 }}>
              Flow Direction
            </p>
            <div className={s.grid2}>
              <label className={s.field}>
                <span className={s.fieldLabel}><Lbl k="PropagationDir">Propagation direction</Lbl></span>
                <div className={s.inputRow}>
                  <input className={s.inp} type="number" value={p.PropagationDir} onChange={setNum("PropagationDir")} step="1" />
                  <span className={s.unit}>°</span>
                </div>
                <span className={s.hint}>Met. convention — 0° = wind from North</span>
              </label>
              <label className={s.field}>
                <span className={s.fieldLabel}><Lbl k="VFlowAng">Upflow angle</Lbl></span>
                <div className={s.inputRow}>
                  <input className={s.inp} type="number" value={p.VFlowAng} onChange={setNum("VFlowAng")} step="0.5" />
                  <span className={s.unit}>°</span>
                </div>
                <span className={s.hint}>Vertical flow inclination</span>
              </label>
            </div>

            {/* Velocity Output Point */}
            <p className={s.sectionHead}>Velocity Output Point</p>
            <div className={s.grid2}>
              <label className={s.field}>
                <span className={s.fieldLabel}><Lbl k="WindVziList">Hub height (Z)</Lbl></span>
                <div className={s.inputRow}>
                  <input className={s.inp} type="number" value={p.WindVziList} onChange={setNum("WindVziList")} />
                  <span className={s.unit}>m</span>
                </div>
                <span className={s.hint}>Match ElastoDyn HubHt</span>
              </label>
              <div className={s.field}>
                <span className={s.fieldLabel}><Lbl k="SumPrint">Summary file</Lbl></span>
                <Toggle
                  value={p.SumPrint}
                  onChange={v => setP(prev => ({ ...prev, SumPrint: v }))}
                  label="Write .IfW.sum"
                />
              </div>
            </div>

            {/* ── Create new file — only shown when no file is currently loaded ── */}
            {!filePath && (
              <>
                <p className={s.sectionHead}>Create file</p>
                <div className={s.outputRow}>
                  <div className={s.autoNameBox}>
                    <span className={s.autoNameLabel}>Auto-name</span>
                    <span className={s.autoNameVal}>{autoName}</span>
                  </div>
                  <label className={s.field} style={{ marginTop: 8 }}>
                    <span className={s.fieldLabel}>
                      Custom filename <span className={s.unit}>(optional override)</span>
                    </span>
                    <input
                      className={s.inp}
                      type="text"
                      value={customDatName}
                      placeholder={autoName}
                      onChange={e => setCustomDatName(e.target.value)}
                    />
                  </label>
                  {project && (
                    <span className={s.hint} style={{ marginTop: 4 }}>
                      → {project.modelDir ?? project.workingDir}/{effectiveDatName}
                    </span>
                  )}
                </div>
                <div className={s.actionRow}>
                  <button
                    className={s.writeBtn}
                    onClick={handleGenerate}
                    disabled={generating || !project}
                    title={!project ? "Select a project folder first" : undefined}
                    type="button"
                  >
                    {generating ? "Writing…" : `Generate ${effectiveDatName}`}
                  </button>
                </div>
              </>
            )}


          </div>
        </div>

        {/* ── Stats sidebar ──────────────────────────────────────────────── */}
        <div className={s.statsPanel}>
          <span className={s.statsLabel}>Quick stats</span>
          <div className={s.turbineWrap}>
            <WindVizSVG windType={p.WindType} windSpeed={p.HWindSpeed} plExp={p.PLexp} />
          </div>
          <div className={s.statsGrid}>
            {stats.map(({ k, v }) => (
              <div key={k} className={s.statCard}>
                <span className={s.statKey}>{k}</span>
                <span className={s.statVal}>{v}</span>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
