import { useState, useEffect, useCallback, useMemo, useRef, createContext, useContext } from "react";
import { createPortal } from "react-dom";
import { invoke } from "@tauri-apps/api/core";
import { open as openDialog } from "@tauri-apps/plugin-dialog";
import { Cloud, FolderOpen, RefreshCw, Eye, Save, ChevronDown, ChevronRight, AlertTriangle, List } from "lucide-react";
import InfoPopover from "../InfoPopover";
import RawFileModal from "../RawFileModal";
import s from "./InflowWindPanel.module.css";

const ACCENT = "#378ADD";

// ── Missing-fields context ────────────────────────────────────────────────────
const MissingCtx = createContext(new Set());

// ── Field info ────────────────────────────────────────────────────────────────
const INFO = {
  WindType: {
    param: "WindType",
    desc: "Selects the wind input model. Type 3 (TurbSim BTS) is the standard choice for stochastic IEC wind fields generated by TurbSim.",
    range: "1–7",
    default: "3",
  },
  PropagationDir: {
    param: "PropagationDir",
    desc: "Direction the wind is travelling using meteorological convention: 0° = wind blowing from North, 90° = wind blowing from East.",
    range: "−180° to 180°",
    default: "0°",
    unit: "degrees",
  },
  VFlowAng: {
    param: "VFlowAng",
    desc: "Vertical inclination of the mean flow. Positive = upslope flow. Typically 0° for flat terrain; may be non-zero for complex terrain studies.",
    range: "−45° to 45°",
    default: "0°",
    unit: "degrees",
  },
  VelInterpCubic: {
    param: "VelInterpCubic",
    desc: "When True, uses cubic (rather than linear) interpolation in time for wind velocity lookups. Cubic is smoother but costs ~30% more CPU. Not used for WindType=1 (Steady).",
    default: "False",
  },
  NWindVel: {
    param: "NWindVel",
    desc: "Number of wind velocity output points (0–9). InflowWind evaluates the total wind velocity at each point and writes it to the OpenFAST output file.",
    range: "0–9",
    default: "1",
  },
  WindVxiList: {
    param: "WindVxiList",
    desc: "X-coordinate (streamwise, positive downwind) of the wind velocity output point(s). Use 0 for the tower centreline.",
    unit: "m",
    default: "0",
  },
  WindVyiList: {
    param: "WindVyiList",
    desc: "Y-coordinate (lateral) of the wind velocity output point(s). Use 0 for the tower centreline.",
    unit: "m",
    default: "0",
  },
  WindVziList: {
    param: "WindVziList",
    desc: "Height at which InflowWind writes out point wind velocity to the OpenFAST output file. Should match HubHt in ElastoDyn so hub-height wind speed appears in results.",
    unit: "m",
    note: "Tip: set this equal to the ElastoDyn HubHt parameter.",
  },
  Echo: {
    param: "Echo",
    desc: "When True, InflowWind writes all input data to a <RootName>.IfW.echo file. Useful for diagnosing input file parsing issues.",
    default: "False",
  },
  HWindSpeed: {
    param: "HWindSpeed",
    desc: "Mean horizontal wind speed at the reference height. Used only for WindType=1 (Steady). AeroDyn will see this speed at every grid point.",
    unit: "m/s",
    default: "12.0",
  },
  RefHt: {
    param: "RefHt",
    desc: "Height at which HWindSpeed is defined. The power law profile U(z) = HWindSpeed × (z/RefHt)^PLexp is applied above and below this height.",
    unit: "m",
    default: "hub height",
  },
  PLexp: {
    param: "PLexp",
    desc: "Wind shear exponent α in the power law profile U(z) ∝ z^α. IEC 61400-1 default is 0.2 for land-based turbines; offshore typically 0.14.",
    range: "0.05–0.40",
    default: "0.2",
    note: "IEC 61400-1 Ed.3 §6.3 specifies α = 0.2 unless site-specific data is available.",
  },
  Filename_Uni: {
    param: "Filename_Uni",
    desc: "Path to the Uniform wind time-series file (.wnd). Each row contains: Time, HorSpd, WindDir, VertSpd, HorShr, VerShr, LnVShr, GstSpd.",
    note: "Uniform wind files can be created manually or with the InflowWind pre-processor.",
  },
  RefHt_Uni: {
    param: "RefHt_Uni",
    desc: "Height at which HorSpd in the .wnd file is defined. Wind profile shear is applied relative to this height.",
    unit: "m",
  },
  RefLength: {
    param: "RefLength",
    desc: "Reference length used to non-dimensionalise the horizontal and vertical shear columns in the Uniform wind file.",
    unit: "m",
  },
  FileName_BTS: {
    param: "FileName_BTS",
    desc: "Path to the TurbSim binary full-field wind file (.bts). Must match the grid dimensions (HubHt, GridHeight, GridWidth) used in the OpenFAST model.",
    note: "Use 'Scan project' to auto-discover .bts files generated by TurbSim or DLC Batch.",
  },
  FilenameRoot: {
    param: "FilenameRoot",
    desc: "Root name of the Bladed-style wind files. For WindType=4 InflowWind appends '.wnd' (binary) and '.sum' (header). For WindType=7 this is the name of the file containing wind scaling values.",
  },
  TowerFile: {
    param: "TowerFile",
    desc: "When True, InflowWind reads a tower wind file (<RootName>.twr) that provides wind speed at tower stations for aerodynamic tower loading. Ignored for WindType=7.",
    default: "False",
  },
  FileName_u: {
    param: "FileName_u",
    desc: "HAWC2 binary file containing the longitudinal (u) component of the fluctuating wind field.",
  },
  FileName_v: {
    param: "FileName_v",
    desc: "HAWC2 binary file containing the lateral (v) component of the fluctuating wind field.",
  },
  FileName_w: {
    param: "FileName_w",
    desc: "HAWC2 binary file containing the vertical (w) component of the fluctuating wind field.",
  },
  nx: {
    param: "nx",
    desc: "Number of grid points in the x (streamwise) direction in the HAWC2 wind box.",
  },
  ny: {
    param: "ny",
    desc: "Number of grid points in the y (lateral) direction in the HAWC2 wind box.",
  },
  nz: {
    param: "nz",
    desc: "Number of grid points in the z (vertical) direction in the HAWC2 wind box.",
  },
  dx: {
    param: "dx",
    desc: "Grid spacing in the x (streamwise) direction (m). Total wind field length = nx × dx.",
    unit: "m",
  },
  dy: {
    param: "dy",
    desc: "Grid spacing in the y (lateral) direction (m). Grid width = (ny−1) × dy.",
    unit: "m",
  },
  dz: {
    param: "dz",
    desc: "Grid spacing in the z (vertical) direction (m). Grid height = (nz−1) × dz.",
    unit: "m",
  },
  RefHt_Hawc: {
    param: "RefHt_Hawc",
    desc: "Reference height for the HAWC2 mean wind profile. The mean wind speed URef is defined at this height.",
    unit: "m",
  },
  ScaleMethod: {
    param: "ScaleMethod",
    desc: "Turbulence scaling method for HAWC2 files: 0 = no scaling (use raw values), 1 = direct scale factors (SFx/SFy/SFz), 2 = scale to achieve target standard deviation (SigmaFx/SigmaFy/SigmaFz).",
    range: "0, 1, 2",
    default: "1",
  },
  URef: {
    param: "URef",
    desc: "Mean u-component wind speed at the HAWC2 reference height. Added to the fluctuating field to produce the total wind field.",
    unit: "m/s",
  },
  WindProfile: {
    param: "WindProfile",
    desc: "Mean wind profile type for the HAWC2 mean wind: 0 = constant (use URef everywhere), 1 = logarithmic (requires Z0), 2 = power law (requires PLExp_Hawc).",
    range: "0=constant, 1=log, 2=power law",
    default: "1",
  },
  PLExp_Hawc: {
    param: "PLExp_Hawc",
    desc: "Power law wind shear exponent for the HAWC2 mean wind profile (WindProfile=2). Same physical meaning as PLexp for steady wind.",
    default: "0.2",
  },
  Z0: {
    param: "Z0",
    desc: "Surface roughness length for the logarithmic HAWC2 mean wind profile. Typical offshore: 0.03 m; typical onshore: 0.05–0.5 m.",
    unit: "m",
    default: "0.03",
  },
  XOffset: {
    param: "XOffset",
    desc: "Initial x-direction offset of the HAWC2 wind box origin from the rotor plane (m). Positive = wind box starts downstream.",
    unit: "m",
    default: "0",
  },
  UserFile: {
    param: "UserFile",
    desc: "Path to the user-defined wind DLL for WindType=6. The DLL must implement the InflowWind user-defined wind interface. All DLL-specific parameters must be configured directly in the .dat file.",
  },
  // LIDAR
  SensorType: {
    param: "SensorType",
    desc: "Lidar sensor type. 0 = None (no lidar modelling). The lidar section is inactive unless SensorType > 0.",
    range: "0=None, 1=Pulsed, 2=Continuous wave",
    default: "0",
  },
  NumPulseGate: {
    param: "NumPulseGate",
    desc: "Number of measurement range gates for a pulsed lidar (SensorType=1). Determines how many points along the beam are sampled.",
    range: "0–100",
    default: "0",
  },
  PulseSpacing: {
    param: "PulseSpacing",
    desc: "Distance between successive range gates along the lidar beam (m).",
    unit: "m",
    default: "30",
  },
  NumBeam: {
    param: "NumBeam",
    desc: "Number of lidar scanning beams (0–5). A 0-beam lidar measures only along its own pointing axis.",
    range: "0–5",
    default: "0",
  },
  FocalDistanceX: {
    param: "FocalDistanceX",
    desc: "X-component (downwind positive) of the focal point distance vector from the lidar origin to the measurement volume (m).",
    unit: "m",
    default: "-200",
  },
  FocalDistanceY: {
    param: "FocalDistanceY",
    desc: "Y-component (lateral) of the focal point distance vector (m).",
    unit: "m",
    default: "0",
  },
  FocalDistanceZ: {
    param: "FocalDistanceZ",
    desc: "Z-component (vertical) of the focal point distance vector (m).",
    unit: "m",
    default: "0",
  },
  RotorApexOffsetPos: {
    param: "RotorApexOffsetPos",
    desc: "X Y Z offset of the lidar sensor from the rotor apex (m), in the lidar coordinate system. Enter as three space-separated values.",
    unit: "m m m",
    default: "0.0 0.0 0.0",
  },
  URefLid: {
    param: "URefLid",
    desc: "Reference mean wind speed used to non-dimensionalise the lidar measurement (m/s).",
    unit: "m/s",
    default: "0",
  },
  MeasurementInterval: {
    param: "MeasurementInterval",
    desc: "Time between successive lidar measurements (s). Determines the temporal resolution of the lidar preview signal.",
    unit: "s",
    default: "0.25",
  },
  LidRadialVel: {
    param: "LidRadialVel",
    desc: "When True, the lidar returns the radial (line-of-sight) velocity component. When False it returns the full u-component velocity.",
    default: "False",
  },
  ConsiderHubMotion: {
    param: "ConsiderHubMotion",
    desc: "When 1, hub motion from the structural model is included in the lidar measurement, making the preview more physically accurate.",
    range: "0=no, 1=yes",
    default: "1",
  },
  SumPrint: {
    param: "SumPrint",
    desc: "When True, InflowWind writes a <RootName>.IfW.sum summary file with mean wind speed, turbulence intensity, and power spectral density at the output point.",
    default: "False",
  },
  OutList: {
    param: "OutList",
    desc: "List of output channel names. One per line. Common channels: Wind1VelX, Wind1VelY, Wind1VelZ. Quotes are optional — added automatically on save.",
  },
};

// ── Wind types ────────────────────────────────────────────────────────────────
const WIND_TYPES = [
  { value: 1, label: "Steady",        desc: "Constant mean speed + power law shear" },
  { value: 3, label: "TurbSim BTS",   desc: "Binary full-field wind file from TurbSim (.bts)" },
  { value: 2, label: "Uniform",       desc: "Time-varying uniform wind from .wnd file" },
  { value: 4, label: "Bladed FF",     desc: "Binary Bladed-style full-field wind (.wnd + .sum)" },
  { value: 5, label: "HAWC2",         desc: "HAWC-format binary wind files (u/v/w components)" },
  { value: 6, label: "User DLL",      desc: "User-defined wind from external DLL (WindType=6)" },
  { value: 7, label: "Native Bladed", desc: "Native Bladed FF with wind scaling values file" },
];

// ── Which tab each field lives on (for missing-field banner jump links) ───────
const FIELD_TAB = {
  WindType:"source",   VelInterpCubic:"source",
  HWindSpeed:"source", RefHt:"source",     PLexp:"source",
  Filename_Uni:"source", RefHt_Uni:"source", RefLength:"source",
  FileName_BTS:"source",
  FilenameRoot:"source", TowerFile:"source",
  FileName_u:"source", FileName_v:"source", FileName_w:"source",
  nx:"source", ny:"source", nz:"source",
  dx:"source", dy:"source", dz:"source",
  RefHt_Hawc:"source", ScaleMethod:"source",
  SFx:"source", SFy:"source", SFz:"source",
  SigmaFx:"source", SigmaFy:"source", SigmaFz:"source",
  URef:"source", WindProfile:"source", PLExp_Hawc:"source", Z0:"source", XOffset:"source",
  UserFile:"source",
  PropagationDir:"flow", VFlowAng:"flow",
  NWindVel:"flow", WindVxiList:"flow", WindVyiList:"flow", WindVziList:"flow",
  SensorType:"lidar", NumPulseGate:"lidar", PulseSpacing:"lidar",
  NumBeam:"lidar", FocalDistanceX:"lidar", FocalDistanceY:"lidar", FocalDistanceZ:"lidar",
  RotorApexOffsetPos:"lidar", URefLid:"lidar", MeasurementInterval:"lidar",
  LidRadialVel:"lidar", ConsiderHubMotion:"lidar",
  SumPrint:"output", Echo:"output",
};

// ── Tabs ──────────────────────────────────────────────────────────────────────
const TABS = [
  { id: "source", label: "Source"  },
  { id: "flow",   label: "Flow"    },
  { id: "lidar",  label: "LIDAR"   },
  { id: "output", label: "Output"  },
];

// ── Keys that are relevant regardless of WindType (for missing-fields filter) ─
const COMMON_KEYS = new Set([
  "WindType","PropagationDir","VFlowAng","VelInterpCubic",
  "NWindVel","WindVxiList","WindVyiList","WindVziList",
  "Echo","SumPrint",
  "SensorType","NumPulseGate","PulseSpacing","NumBeam",
  "FocalDistanceX","FocalDistanceY","FocalDistanceZ",
  "RotorApexOffsetPos","URefLid","MeasurementInterval",
  "LidRadialVel","ConsiderHubMotion",
]);

// Keys that are only relevant for a specific WindType
const TYPE_KEYS = {
  1: new Set(["HWindSpeed","RefHt","PLexp"]),
  2: new Set(["Filename_Uni","RefHt_Uni","RefLength"]),
  3: new Set(["FileName_BTS"]),
  4: new Set(["FilenameRoot","TowerFile"]),
  5: new Set([
    "FileName_u","FileName_v","FileName_w",
    "nx","ny","nz","dx","dy","dz","RefHt_Hawc",
    "ScaleMethod","SFx","SFy","SFz","SigmaFx","SigmaFy","SigmaFz",
    "URef","WindProfile","PLExp_Hawc","Z0","XOffset",
  ]),
  6: new Set(["UserFile"]),
  7: new Set(["FilenameRoot"]),
};

// ── Output variable catalogue ─────────────────────────────────────────────────
const OUT_VARS = [
  {
    group: "Wind Velocity at Output Points",
    vars: [
      { name: "Wind1VelX", desc: "X-dir (streamwise) velocity at output point 1",         unit: "m/s" },
      { name: "Wind1VelY", desc: "Y-dir (lateral) velocity at output point 1",             unit: "m/s" },
      { name: "Wind1VelZ", desc: "Z-dir (vertical) velocity at output point 1",            unit: "m/s" },
      { name: "Wind2VelX", desc: "X-dir velocity at output point 2 (requires NWindVel ≥ 2)", unit: "m/s" },
      { name: "Wind2VelY", desc: "Y-dir velocity at output point 2",                       unit: "m/s" },
      { name: "Wind2VelZ", desc: "Z-dir velocity at output point 2",                       unit: "m/s" },
      { name: "Wind3VelX", desc: "X-dir velocity at output point 3 (requires NWindVel ≥ 3)", unit: "m/s" },
      { name: "Wind3VelY", desc: "Y-dir velocity at output point 3",                       unit: "m/s" },
      { name: "Wind3VelZ", desc: "Z-dir velocity at output point 3",                       unit: "m/s" },
    ],
  },
  {
    group: "Hub-Height Wind",
    vars: [
      { name: "HHWndSpd", desc: "Hub-height horizontal wind speed (magnitude)",   unit: "m/s" },
      { name: "HHWndDir", desc: "Hub-height wind direction, meteorological convention", unit: "deg" },
      { name: "HHWndVx",  desc: "Hub-height U-component (streamwise)",             unit: "m/s" },
      { name: "HHWndVy",  desc: "Hub-height V-component (lateral)",               unit: "m/s" },
      { name: "HHWndVz",  desc: "Hub-height W-component (vertical)",              unit: "m/s" },
    ],
  },
  {
    group: "Rotor-Disk Averages",
    vars: [
      { name: "RtFldFxh",   desc: "Rotor-disk-averaged X-dir wind force, hub frame",  unit: "N"   },
      { name: "RtFldFyh",   desc: "Rotor-disk-averaged Y-dir wind force, hub frame",  unit: "N"   },
      { name: "RtFldFzh",   desc: "Rotor-disk-averaged Z-dir wind force, hub frame",  unit: "N"   },
      { name: "RtFldMxh",   desc: "Rotor-disk-averaged X-dir moment, hub frame",      unit: "N·m" },
      { name: "RtFldMyh",   desc: "Rotor-disk-averaged Y-dir moment, hub frame",      unit: "N·m" },
      { name: "RtFldMzh",   desc: "Rotor-disk-averaged Z-dir moment, hub frame",      unit: "N·m" },
      { name: "RtFldCdEff", desc: "Rotor-disk-averaged effective drag coefficient",   unit: "-"   },
      { name: "RtFldDynP",  desc: "Rotor-disk-averaged dynamic pressure",            unit: "Pa"  },
      { name: "RtFldSkew",  desc: "Inflow skew angle at rotor disk",                 unit: "deg" },
    ],
  },
];

// ── Auto-name helper ──────────────────────────────────────────────────────────
function autoFilename(windType, p) {
  if (windType === 1) {
    const v = String(Number(p.HWindSpeed).toFixed(1)).replace(".", "p");
    return `IFW_Steady_V${v}.dat`;
  }
  if (windType === 2 && p.Filename_Uni.trim() && p.Filename_Uni !== "none") {
    const base = p.Filename_Uni.trim().split(/[\\/]/).pop().replace(/\.wnd$/i, "");
    return `IFW_Uni_${base}.dat`;
  }
  if (windType === 3 && p.FileName_BTS.trim()) {
    const base = p.FileName_BTS.trim().split(/[\\/]/).pop().replace(/\.bts$/i, "");
    return `IFW_${base}.dat`;
  }
  if ((windType === 4 || windType === 7) && p.FilenameRoot.trim() && p.FilenameRoot !== "none") {
    const base = p.FilenameRoot.trim().split(/[\\/]/).pop().replace(/\.(wnd|sum)$/i, "");
    return windType === 7 ? `IFW_NBladed_${base}.dat` : `IFW_Bladed_${base}.dat`;
  }
  if (windType === 4) return "IFW_Bladed.dat";
  if (windType === 5) return "IFW_HAWC2.dat";
  if (windType === 6) return "IFW_UserDLL.dat";
  if (windType === 7) return "IFW_NativeBladed.dat";
  return "InflowWind.dat";
}

// ── Default parameters ────────────────────────────────────────────────────────
const DEFAULT = {
  WindType:       3,
  PropagationDir: 0.0,
  VFlowAng:       0.0,
  VelInterpCubic: false,
  NWindVel:       1,
  WindVxiList:    0.0,
  WindVyiList:    0.0,
  WindVziList:    90.0,
  Echo:           false,
  // Steady (type 1)
  HWindSpeed:     12.0,
  RefHt:          90.0,
  PLexp:          0.2,
  // Uniform (type 2)
  Filename_Uni:   "none",
  RefHt_Uni:      90.0,
  RefLength:      126.0,
  // TurbSim BTS (type 3)
  FileName_BTS:   "",
  // Bladed FF (types 4 & 7)
  FilenameRoot:   "none",
  TowerFile:      false,
  // User DLL (type 6)
  UserFile:       "none",
  // HAWC2 (type 5) — files
  FileName_u:     "none",
  FileName_v:     "none",
  FileName_w:     "none",
  // HAWC2 grid
  nx: 64, ny: 32, nz: 32,
  dx: 25.0, dy: 2.0, dz: 2.0,
  RefHt_Hawc: 90.0,
  // HAWC2 turbulence scaling
  ScaleMethod: 1,
  SFx: 1.0, SFy: 1.0, SFz: 1.0,
  SigmaFx: 1.2, SigmaFy: 0.8, SigmaFz: 0.2,
  // HAWC2 mean wind
  URef:       12.0,
  WindProfile: 1,
  PLExp_Hawc:  0.2,
  Z0:          0.03,
  XOffset:     0,
  // LIDAR
  SensorType:          0,
  NumPulseGate:        0,
  PulseSpacing:        30.0,
  NumBeam:             0,
  FocalDistanceX:      -200.0,
  FocalDistanceY:      0.0,
  FocalDistanceZ:      0.0,
  RotorApexOffsetPos:  "0.0 0.0 0.0",
  URefLid:             0.0,
  MeasurementInterval: 0.25,
  LidRadialVel:        false,
  ConsiderHubMotion:   1,
  // Output
  SumPrint: false,
  OutList:  '"Wind1VelX"\n"Wind1VelY"\n"Wind1VelZ"',
};

// ── Parser ────────────────────────────────────────────────────────────────────
function parseInflowWindFile(content) {
  const kv = {};
  let inOutList = false;
  const outListLines = [];

  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("!") || line.startsWith("=") || /^-{3,}/.test(line)) continue;

    if (inOutList) {
      if (/^END\b/i.test(line)) { inOutList = false; continue; }
      const m = line.match(/^"([^"]+)"/);
      if (m) outListLines.push(`"${m[1]}"`);
      continue;
    }

    let rest = line;
    let value;

    if (rest.startsWith('"')) {
      const end = rest.indexOf('"', 1);
      if (end < 0) continue;
      value = rest.slice(1, end);
      rest  = rest.slice(end + 1).trim();
    } else {
      // Multi-value aware: collect all leading numeric/boolean tokens before the first identifier
      const tokens = rest.split(/\s+/).filter(t => t);
      const valueTokens = [];
      let keyIdx = -1;
      for (let j = 0; j < tokens.length; j++) {
        const t = tokens[j];
        if (/^[A-Za-z_]/.test(t) && !/^(true|false|default)$/i.test(t) && !/[./\\]/.test(t)) {
          keyIdx = j; break;
        }
        valueTokens.push(t);
      }
      if (keyIdx < 0) continue;
      value = valueTokens.join(" ");
      rest  = tokens.slice(keyIdx).join(" ");
    }

    const keyMatch = rest.match(/^([A-Za-z_][A-Za-z0-9_]*)/);
    if (!keyMatch) continue;
    const key = keyMatch[1];

    if (key.toLowerCase() === "outlist") { inOutList = true; continue; }
    kv[key] = value;
  }

  if (outListLines.length) kv["__OutList__"] = outListLines.join("\n");
  return kv;
}

function parsedToState(kv) {
  const bool = (k, d) => (k in kv ? kv[k].toLowerCase() === "true" : d);
  const num  = (k, d) => { if (!(k in kv)) return d; const v = parseFloat(kv[k]); return isNaN(v) ? d : v; };
  const str  = (k, d) => (k in kv ? kv[k].replace(/^"|"$/g, "") : d);

  return {
    ...DEFAULT,
    WindType:       num("WindType",       DEFAULT.WindType),
    PropagationDir: num("PropagationDir", DEFAULT.PropagationDir),
    VFlowAng:       num("VFlowAng",       DEFAULT.VFlowAng),
    VelInterpCubic: bool("VelInterpCubic",DEFAULT.VelInterpCubic),
    NWindVel:       num("NWindVel",       DEFAULT.NWindVel),
    WindVxiList:    num("WindVxiList",    DEFAULT.WindVxiList),
    WindVyiList:    num("WindVyiList",    DEFAULT.WindVyiList),
    WindVziList:    num("WindVziList",    DEFAULT.WindVziList),
    Echo:           bool("Echo",          DEFAULT.Echo),
    // Steady
    HWindSpeed:     num("HWindSpeed",     DEFAULT.HWindSpeed),
    RefHt:          num("RefHt",          DEFAULT.RefHt),
    PLexp:          num("PLexp",          DEFAULT.PLexp),
    // Uniform
    Filename_Uni:   str("Filename_Uni",   DEFAULT.Filename_Uni),
    RefHt_Uni:      num("RefHt_Uni",      DEFAULT.RefHt_Uni),
    RefLength:      num("RefLength",      DEFAULT.RefLength),
    // BTS
    FileName_BTS:   str("FileName_BTS",   DEFAULT.FileName_BTS),
    // Bladed
    FilenameRoot:   str("FilenameRoot",   DEFAULT.FilenameRoot),
    TowerFile:      bool("TowerFile",     DEFAULT.TowerFile),
    // HAWC2
    FileName_u:     str("FileName_u",     DEFAULT.FileName_u),
    FileName_v:     str("FileName_v",     DEFAULT.FileName_v),
    FileName_w:     str("FileName_w",     DEFAULT.FileName_w),
    nx: num("nx", DEFAULT.nx), ny: num("ny", DEFAULT.ny), nz: num("nz", DEFAULT.nz),
    dx: num("dx", DEFAULT.dx), dy: num("dy", DEFAULT.dy), dz: num("dz", DEFAULT.dz),
    RefHt_Hawc:  num("RefHt_Hawc",  DEFAULT.RefHt_Hawc),
    ScaleMethod: num("ScaleMethod", DEFAULT.ScaleMethod),
    SFx: num("SFx", DEFAULT.SFx), SFy: num("SFy", DEFAULT.SFy), SFz: num("SFz", DEFAULT.SFz),
    SigmaFx: num("SigmaFx", DEFAULT.SigmaFx), SigmaFy: num("SigmaFy", DEFAULT.SigmaFy), SigmaFz: num("SigmaFz", DEFAULT.SigmaFz),
    URef:        num("URef",        DEFAULT.URef),
    WindProfile: num("WindProfile", DEFAULT.WindProfile),
    PLExp_Hawc:  num("PLExp_Hawc",  DEFAULT.PLExp_Hawc),
    Z0:          num("Z0",          DEFAULT.Z0),
    XOffset:     num("XOffset",     DEFAULT.XOffset),
    // User DLL
    UserFile: str("UserFile", DEFAULT.UserFile),
    // LIDAR
    SensorType:          num("SensorType",          DEFAULT.SensorType),
    NumPulseGate:        num("NumPulseGate",        DEFAULT.NumPulseGate),
    PulseSpacing:        num("PulseSpacing",        DEFAULT.PulseSpacing),
    NumBeam:             num("NumBeam",             DEFAULT.NumBeam),
    FocalDistanceX:      num("FocalDistanceX",      DEFAULT.FocalDistanceX),
    FocalDistanceY:      num("FocalDistanceY",      DEFAULT.FocalDistanceY),
    FocalDistanceZ:      num("FocalDistanceZ",      DEFAULT.FocalDistanceZ),
    RotorApexOffsetPos:  kv.RotorApexOffsetPos ? kv.RotorApexOffsetPos.replace(/^"|"$/g, "") : DEFAULT.RotorApexOffsetPos,
    URefLid:             num("URefLid",             DEFAULT.URefLid),
    MeasurementInterval: num("MeasurementInterval", DEFAULT.MeasurementInterval),
    LidRadialVel:        bool("LidRadialVel",       DEFAULT.LidRadialVel),
    ConsiderHubMotion:   num("ConsiderHubMotion",   DEFAULT.ConsiderHubMotion),
    // Output
    SumPrint: bool("SumPrint", DEFAULT.SumPrint),
    OutList:  kv["__OutList__"] || DEFAULT.OutList,
    __rawKV__: kv,
  };
}

// ── Builder ───────────────────────────────────────────────────────────────────
function buildInflowWindContent(p) {
  const b   = v  => (v ? "True" : "False");
  const r   = v  => { const n = Number(v); return isNaN(n) ? String(v) : String(n); };
  const pad = sv => String(sv).padEnd(14);
  const q   = v  => `"${v}"`;

  const WRITTEN = new Set([
    "Echo","WindType","PropagationDir","VFlowAng","VelInterpCubic",
    "NWindVel","WindVxiList","WindVyiList","WindVziList",
    "HWindSpeed","RefHt","PLexp",
    "Filename_Uni","RefHt_Uni","RefLength",
    "FileName_BTS",
    "FilenameRoot","TowerFile",
    "UserFile",
    "FileName_u","FileName_v","FileName_w",
    "nx","ny","nz","dx","dy","dz","RefHt_Hawc",
    "ScaleMethod","SFx","SFy","SFz","SigmaFx","SigmaFy","SigmaFz",
    "URef","WindProfile","PLExp_Hawc","Z0","XOffset",
    "SensorType","NumPulseGate","PulseSpacing","NumBeam",
    "FocalDistanceX","FocalDistanceY","FocalDistanceZ",
    "RotorApexOffsetPos","URefLid","MeasurementInterval","LidRadialVel","ConsiderHubMotion",
    "SumPrint","OutList",
  ]);
  const rawKV = p.__rawKV__ || {};
  const passThrough = Object.entries(rawKV)
    .filter(([k]) => !WRITTEN.has(k) && !k.startsWith("__"))
    .map(([k, v]) => `${String(v).padEnd(14)} ${k}`);

  const outLines = (p.OutList || "")
    .split("\n").map(l => l.trim()).filter(l => l)
    .map(l => l.startsWith('"') ? l : `"${l}"`);

  const lines = [
    `------- InflowWind v3.01.* INPUT FILE ----------------------------------------`,
    `InflowWind input file generated by FlowUrja Studio`,
    `------- SIMULATION CONTROL ---------------------------------------------------`,
    `${pad(b(p.Echo))} Echo            - Echo input data to <RootName>.IfW.echo (flag)`,
    `${pad(r(p.WindType))} WindType        - Wind model {1=Steady;2=Uniform;3=TurbSim BTS;4=Bladed FF;5=HAWC2;6=User DLL;7=Native Bladed} (-)`,
    `${pad(r(p.PropagationDir))} PropagationDir  - Wind propagation direction — meteorological convention (degrees)`,
    `${pad(r(p.VFlowAng))} VFlowAng        - Upflow angle (degrees, about y-axis)`,
    `${pad(b(p.VelInterpCubic))} VelInterpCubic  - Cubic temporal interpolation (flag)`,
    `${pad(r(p.NWindVel))} NWindVel        - Number of wind velocity output points [0–9] (-)`,
    `${pad(r(p.WindVxiList))} WindVxiList     - X-coordinates for wind velocity output (m)`,
    `${pad(r(p.WindVyiList))} WindVyiList     - Y-coordinates for wind velocity output (m)`,
    `${pad(r(p.WindVziList))} WindVziList     - Z-coordinates for wind velocity output (m)`,
    `================== Parameters for Steady Wind [WindType=1] ====================`,
    `${pad(r(p.HWindSpeed))} HWindSpeed      - Horizontal wind speed (m/s)`,
    `${pad(r(p.RefHt))} RefHt           - Reference height for wind speed (m)`,
    `${pad(r(p.PLexp))} PLexp           - Power law exponent (-)`,
    `================== Parameters for Uniform Wind [WindType=2] ===================`,
    `${pad(q(p.Filename_Uni))} Filename_Uni    - Uniform wind file (.wnd)`,
    `${pad(r(p.RefHt_Uni))} RefHt_Uni       - Reference height for uniform wind (m)`,
    `${pad(r(p.RefLength))} RefLength       - Reference length for shear (m)`,
    `================== Parameters for Binary TurbSim FF [WindType=3] ==============`,
    `${pad(q(p.FileName_BTS))} FileName_BTS    - TurbSim binary wind field file (.bts)`,
    `================== Parameters for Binary Bladed-style FF [WindType=4] =========`,
    `${pad(q(p.FilenameRoot))} FilenameRoot    - Root name of Bladed FF wind file`,
    `${pad(b(p.TowerFile))} TowerFile       - Have tower file (.twr) (flag)`,
    `================== Parameters for HAWC-format binary files [WindType=5] =======`,
    `${pad(q(p.FileName_u))} FileName_u      - u-component wind file (.bin)`,
    `${pad(q(p.FileName_v))} FileName_v      - v-component wind file (.bin)`,
    `${pad(q(p.FileName_w))} FileName_w      - w-component wind file (.bin)`,
    `${pad(r(p.nx))} nx              - grids in x (-)`,
    `${pad(r(p.ny))} ny              - grids in y (-)`,
    `${pad(r(p.nz))} nz              - grids in z (-)`,
    `${pad(r(p.dx))} dx              - x grid spacing (m)`,
    `${pad(r(p.dy))} dy              - y grid spacing (m)`,
    `${pad(r(p.dz))} dz              - z grid spacing (m)`,
    `${pad(r(p.RefHt_Hawc))} RefHt_Hawc      - HAWC reference height (m)`,
    `${pad(r(p.ScaleMethod))} ScaleMethod     - Turbulence scaling method (-)`,
    `${pad(r(p.SFx))} SFx             - x scaling factor (-)`,
    `${pad(r(p.SFy))} SFy             - y scaling factor (-)`,
    `${pad(r(p.SFz))} SFz             - z scaling factor (-)`,
    `${pad(r(p.SigmaFx))} SigmaFx         - x turbulence std dev target (m/s)`,
    `${pad(r(p.SigmaFy))} SigmaFy         - y turbulence std dev target (m/s)`,
    `${pad(r(p.SigmaFz))} SigmaFz         - z turbulence std dev target (m/s)`,
    `${pad(r(p.URef))} URef            - Mean u-component at reference height (m/s)`,
    `${pad(r(p.WindProfile))} WindProfile     - Wind profile type (0=const; 1=log; 2=power law) (-)`,
    `${pad(r(p.PLExp_Hawc))} PLExp_Hawc      - Power law exponent for HAWC (-)`,
    `${pad(r(p.Z0))} Z0              - Surface roughness length (m)`,
    `${pad(r(p.XOffset))} XOffset         - Initial x offset (m)`,
    `================== Parameters for User-Defined wind [WindType=6] ==============`,
    `${pad(q(p.UserFile))} UserFile        - Path to user-defined DLL wind file`,
    `================== LIDAR Parameters ==========================================`,
    `${pad(r(p.SensorType))} SensorType          - Lidar sensor type (0=None) (-)`,
    `${pad(r(p.NumPulseGate))} NumPulseGate        - Number of lidar measurement gates (-)`,
    `${pad(r(p.PulseSpacing))} PulseSpacing        - Distance between range gates (m)`,
    `${pad(r(p.NumBeam))} NumBeam             - Number of lidar beams (0-5)`,
    `${pad(r(p.FocalDistanceX))} FocalDistanceX      - Focal distance X (m)`,
    `${pad(r(p.FocalDistanceY))} FocalDistanceY      - Focal distance Y (m)`,
    `${pad(r(p.FocalDistanceZ))} FocalDistanceZ      - Focal distance Z (m)`,
    `${pad(p.RotorApexOffsetPos)} RotorApexOffsetPos  - Offset of lidar from rotor apex (x y z) (m)`,
    `${pad(r(p.URefLid))} URefLid             - Reference wind speed for lidar (m/s)`,
    `${pad(r(p.MeasurementInterval))} MeasurementInterval - Time between measurements (s)`,
    `${pad(b(p.LidRadialVel))} LidRadialVel        - Return radial component (flag)`,
    `${pad(r(p.ConsiderHubMotion))} ConsiderHubMotion   - Consider hub motion impact on lidar (-)`,
    `================== OUTPUT ====================================================`,
    `${pad(b(p.SumPrint))} SumPrint        - Print summary to <RootName>.IfW.sum (flag)`,
    `              OutList         - The next line(s) contains a list of output parameters.`,
    ...outLines,
    `END of input file (the word "END" must appear in the first 3 columns of this last OutList line)`,
    `---------------------------------------------------------------------------------------`,
  ];

  if (passThrough.length) {
    lines.push(
      "!--- Parameters not editable in this UI (preserved verbatim from original file) ---",
      ...passThrough,
    );
  }

  return lines.join("\n");
}

// ── Sub-components (all at module level — never inside the component) ─────────

function Field({ label, unit, children, hint, info, fieldKey, disabledHint }) {
  const missingSet = useContext(MissingCtx);
  const [hintVisible, setHintVisible] = useState(false);
  const key = fieldKey || label.match(/\(([A-Za-z_][A-Za-z_0-9]*)\)\s*$/)?.[1];
  const isMissing = key && missingSet.size > 0 && missingSet.has(key);
  return (
    <div className={s.field}>
      <div className={s.fieldHeader}>
        <label className={s.fieldLabel}>
          {label}{unit && <span className={s.unit}> {unit}</span>}
        </label>
        {isMissing && <span className={s.defaultBadge}>default</span>}
        {info && (
          <InfoPopover
            accentColor={ACCENT}
            content={typeof info === "string" ? { desc: info } : info}
          />
        )}
      </div>
      <div
        className={isMissing ? s.fieldDefaulted : undefined}
        style={{ position: "relative" }}
        onMouseEnter={() => disabledHint && setHintVisible(true)}
        onMouseLeave={() => setHintVisible(false)}
      >
        {children}
        {disabledHint && hintVisible && (
          <div className={s.disabledHint}>{disabledHint}</div>
        )}
      </div>
      {hint && <span className={s.hint}>{hint}</span>}
    </div>
  );
}

function Toggle({ value, onChange, label, disabled, note }) {
  return (
    <div className={s.toggleRow}>
      <button
        type="button"
        disabled={disabled}
        className={`${s.toggle} ${value ? s.on : ""}`}
        onClick={() => !disabled && onChange(!value)}
      >
        <span className={s.toggleThumb} />
      </button>
      {label && <span className={s.toggleLabel}>{label}</span>}
      {note  && <span className={s.toggleNote}>{note}</span>}
    </div>
  );
}

function Collapsible({ title, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className={s.collapsible}>
      <button className={s.collapsibleHead} onClick={() => setOpen(o => !o)} type="button">
        {open ? <ChevronDown size={13} strokeWidth={2} /> : <ChevronRight size={13} strokeWidth={2} />}
        {title}
      </button>
      {open && <div className={s.collapsibleBody}>{children}</div>}
    </div>
  );
}

function OutVarModal({ current, onClose, onApply }) {
  const [selected, setSelected] = useState(() => {
    const names = (current || "").split("\n")
      .map(l => l.trim().replace(/^"|"$/g, "")).filter(Boolean);
    return new Set(names);
  });
  const [query,   setQuery]   = useState("");
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const raf = requestAnimationFrame(() => setVisible(true));
    return () => cancelAnimationFrame(raf);
  }, []);

  const handleClose = () => {
    setVisible(false);
    setTimeout(onClose, 220);
  };

  const handleApply = () => {
    const outList = [...selected].map(n => `"${n}"`).join("\n");
    onApply(outList);
    handleClose();
  };

  const toggle = (name) =>
    setSelected(prev => { const n = new Set(prev); n.has(name) ? n.delete(name) : n.add(name); return n; });

  const q = query.toLowerCase();
  const filteredGroups = OUT_VARS.map(g => ({
    ...g,
    vars: q ? g.vars.filter(v =>
      v.name.toLowerCase().includes(q) || v.desc.toLowerCase().includes(q) || v.unit.toLowerCase().includes(q)
    ) : g.vars,
  })).filter(g => g.vars.length > 0);

  return createPortal(
    <div
      className={`${s.modalOverlay} ${visible ? s.modalOverlayVisible : ""}`}
      onClick={handleClose}
    >
      <div
        className={`${s.modal} ${visible ? s.modalVisible : ""}`}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className={s.modalHeader}>
          <span className={s.modalTitle}>Output variable picker</span>
          <span className={s.modalCount}>{selected.size} selected</span>
          <div style={{ flex: 1 }} />
          <button className={s.modalClose} onClick={handleClose} type="button">✕</button>
        </div>

        {/* Search */}
        <div className={s.modalSearch}>
          <svg width="13" height="13" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0, opacity: 0.4 }}>
            <circle cx="6.5" cy="6.5" r="5" stroke="currentColor" strokeWidth="1.5"/>
            <line x1="10.5" y1="10.5" x2="14" y2="14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
          </svg>
          <input
            className={s.modalSearchInput}
            placeholder="Search variables… (name, description, unit)"
            value={query}
            onChange={e => setQuery(e.target.value)}
            autoFocus
          />
        </div>

        {/* Variable groups */}
        <div className={s.modalBody}>
          {filteredGroups.map(g => {
            const allOn  = g.vars.every(v => selected.has(v.name));
            const someOn = g.vars.some(v => selected.has(v.name));
            return (
              <div key={g.group} className={s.varGroup}>
                <div className={s.varGroupHead}>
                  <button
                    type="button"
                    className={`${s.groupCheck} ${allOn ? s.groupCheckAll : someOn ? s.groupCheckSome : ""}`}
                    onClick={() => {
                      setSelected(prev => {
                        const n = new Set(prev);
                        if (allOn) g.vars.forEach(v => n.delete(v.name));
                        else       g.vars.forEach(v => n.add(v.name));
                        return n;
                      });
                    }}
                  />
                  <span>{g.group}</span>
                  <span className={s.varGroupCount}>{g.vars.filter(v => selected.has(v.name)).length}/{g.vars.length}</span>
                </div>
                {g.vars.map(v => (
                  <label key={v.name} className={`${s.varRow} ${selected.has(v.name) ? s.varRowOn : ""}`}>
                    <input
                      type="checkbox"
                      className={s.varCheck}
                      checked={selected.has(v.name)}
                      onChange={() => toggle(v.name)}
                    />
                    <span className={s.varName}>{v.name}</span>
                    <span className={s.varUnit}>{v.unit}</span>
                    <span className={s.varDesc}>{v.desc}</span>
                    {selected.has(v.name) && (
                      <svg width="11" height="11" viewBox="0 0 12 12" className={s.varCheck__mark}>
                        <polyline points="1.5,6 4.5,9 10.5,3" stroke={ACCENT} strokeWidth="1.8" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    )}
                  </label>
                ))}
              </div>
            );
          })}
          {filteredGroups.length === 0 && (
            <p className={s.varNoMatch}>No variables match "{query}"</p>
          )}
        </div>

        {/* Footer */}
        <div className={s.modalFooter}>
          <button className={s.modalCancelBtn} onClick={handleClose} type="button">Cancel</button>
          <button className={s.modalApplyBtn} onClick={handleApply} type="button">
            Apply {selected.size} channel{selected.size !== 1 ? "s" : ""}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}

function WindVizSVG({ windType, windSpeed, plExp }) {
  const c = "#378ADD";
  const arrowRows = [[16, 1.00],[29, 0.83],[42, 0.67],[55, 0.52],[68, 0.39]];
  const MAX_LEN = 24;
  return (
    <svg viewBox="0 0 100 110" width="100%" height="180" style={{ display: "block" }}>
      <line x1="68" y1="54" x2="68" y2="100" style={{ stroke: "var(--tx-4)" }} strokeWidth="5" strokeLinecap="round"/>
      <line x1="56" y1="101" x2="80" y2="101" style={{ stroke: "var(--bd-strong)" }} strokeWidth="2"/>
      <rect x="60" y="48" width="16" height="8" rx="2" style={{ fill: "var(--bg-hover-md)" }}/>
      <circle cx="68" cy="52" r="3.5" fill={c}/>
      <line x1="68" y1="48" x2="68" y2="14" stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      <line x1="65" y1="55" x2="42" y2="68" stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      <line x1="71" y1="55" x2="94" y2="68" stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      {arrowRows.map(([y, rel], i) => {
        const len = MAX_LEN * rel;
        const dy  = windType === 3 ? ((i * 7) % 5) - 2 : 0;
        return (
          <g key={y} opacity="0.62">
            <line x1="4" y1={y + dy} x2={4 + len} y2={y + dy}
              stroke={c} strokeWidth="1.4" strokeLinecap="round"/>
            <polyline
              points={`${4 + len - 5},${y + dy - 3.5} ${4 + len},${y + dy} ${4 + len - 5},${y + dy + 3.5}`}
              stroke={c} strokeWidth="1.4" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
          </g>
        );
      })}
      <text x="4" y="108" fontSize="6" style={{ fill: c }} fontFamily="-apple-system,sans-serif" opacity="0.7">
        {windType === 1
          ? `Steady  ${Number(windSpeed || 0).toFixed(1)} m/s  α=${plExp}`
          : windType === 2 ? "Uniform (.wnd)"
          : windType === 3 ? "TurbSim BTS"
          : windType === 5 ? "HAWC2"
          : windType === 6 ? "User DLL"
          : "Bladed FF"}
      </text>
    </svg>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────
export default function InflowWindPanel({
  onLog, project,
  filePathFromProject, reloadKey, onDirtyChange, onRegisterSave,
  onWindParamsChange,
  simRunning = false,
}) {
  const [tab,            setTab]           = useState("source");
  const tabDirRef                         = useRef(1);
  const [p,              _setP]           = useState(DEFAULT);
  const [filePath,       setFilePath]     = useState("");
  const [isDirtyFlag,    setIsDirtyFlag]  = useState(false);
  const [btsFiles,       setBtsFiles]     = useState([]);
  const [scanning,       setScanning]     = useState(false);
  const [showRaw,        setShowRaw]      = useState(false);
  const [rawContent,     setRawContent]   = useState("");
  const [generating,     setGenerating]   = useState(false);
  const [customDatName,  setCustomDatName] = useState("");
  const [showOutVarModal, setShowOutVarModal] = useState(false);
  const originalRef = useRef(null);

  const setP = useCallback((updater) => {
    _setP(updater);
    setIsDirtyFlag(true);
  }, []);

  const isDirty = !!filePath && isDirtyFlag &&
    originalRef.current !== null && JSON.stringify(p) !== originalRef.current;

  useEffect(() => {
    if (!isDirtyFlag || originalRef.current === null) return;
    if (JSON.stringify(p) === originalRef.current) setIsDirtyFlag(false);
  }, [p, isDirtyFlag]); // eslint-disable-line react-hooks/exhaustive-deps

  const setNum = key => e => setP(prev => ({ ...prev, [key]: Number(e.target.value) }));
  const setStr = key => e => setP(prev => ({ ...prev, [key]: e.target.value }));

  const autoName         = useMemo(() => autoFilename(p.WindType, p), [p.WindType, p.HWindSpeed, p.FileName_BTS, p.Filename_Uni, p.FilenameRoot]); // eslint-disable-line react-hooks/exhaustive-deps
  const effectiveDatName = customDatName.trim() || autoName;

  // Detect fields missing from the loaded file (showing defaults).
  // Only flag params that are relevant to the currently active WindType.
  const missingFields = useMemo(() => {
    if (!filePath || !p.__rawKV__) return [];
    const rawKeys    = new Set(Object.keys(p.__rawKV__));
    const activeKeys = new Set([
      ...COMMON_KEYS,
      ...(TYPE_KEYS[p.WindType] || []),
    ]);
    return Object.keys(DEFAULT).filter(k => {
      if (k.startsWith("__")) return false;
      if (typeof DEFAULT[k] === "string" && DEFAULT[k].includes("\n")) return false;
      if (!activeKeys.has(k)) return false;
      return !rawKeys.has(k);
    });
  }, [filePath, p.__rawKV__, p.WindType]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── File operations ────────────────────────────────────────────────────────
  const loadFile = async (path) => {
    try {
      const content  = await invoke("read_text_file", { path });
      const kv       = parseInflowWindFile(content);
      const newState = parsedToState(kv);
      originalRef.current = JSON.stringify(newState);
      _setP(newState);
      setIsDirtyFlag(false);
      onLog?.("ok", `Loaded ${path.split("/").pop()}`);
    } catch {
      const fallback = { ...DEFAULT };
      const content  = buildInflowWindContent(fallback);
      try {
        await invoke("write_text_file", { path, content });
        originalRef.current = JSON.stringify(fallback);
        _setP(fallback);
        onLog?.("info", `${path.split("/").pop()} not found — created with defaults`);
      } catch {}
    }
  };

  const handleOpen = async () => {
    try {
      const f = await openDialog({
        multiple: false, directory: false,
        filters: [{ name: "InflowWind input", extensions: ["dat"] }],
      });
      if (!f) return;
      setFilePath(f);
      await loadFile(f);
    } catch {}
  };

  const handleSave = useCallback(async () => {
    if (simRunning) {
      onLog?.("warn", "⚠ OpenFAST is running — save blocked to protect the active simulation. Wait for it to finish.");
      return;
    }
    if (!filePath) {
      onLog?.("warn", "No file open — use Open .dat or Generate first.");
      return;
    }
    const content = buildInflowWindContent(p);
    try {
      await invoke("write_text_file", { path: filePath, content });
      originalRef.current = JSON.stringify(p);
      setIsDirtyFlag(false);
      onLog?.("ok", `Saved ${filePath.split("/").pop()}`);
    } catch (err) {
      onLog?.("error", `Save failed: ${String(err)}`);
    }
  }, [filePath, p]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleGenerate = async () => {
    if (!project) { onLog?.("warn", "Open a project directory first."); return; }
    if (p.WindType === 3 && !p.FileName_BTS.trim()) { onLog?.("warn", "Select a .bts file first."); return; }
    setGenerating(true);
    const outPath = `${project.modelDir ?? project.workingDir}/${effectiveDatName}`;
    const content = buildInflowWindContent(p);
    try {
      await invoke("write_text_file", { path: outPath, content });
      originalRef.current = JSON.stringify(p);
      setFilePath(outPath);
      setIsDirtyFlag(false);
      onLog?.("ok", `Generated → ${outPath}`);
    } catch (err) {
      onLog?.("error", `Write failed: ${err.message ?? err}`);
    }
    setGenerating(false);
  };

  const handleViewRaw = async () => {
    if (!filePath) {
      onLog?.("warn", "Load or save the InflowWind file first — then View will show the actual file on disk.");
      return;
    }
    try {
      const content = await invoke("read_text_file", { path: filePath });
      setRawContent(content);
      setShowRaw(true);
    } catch (err) {
      onLog?.("error", `Cannot read file: ${err}`);
    }
  };

  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "s") { e.preventDefault(); handleSave(); }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [handleSave]);

  // ── Project integration ────────────────────────────────────────────────────
  useEffect(() => {
    if (!filePathFromProject) return;
    setFilePath(filePathFromProject);
    loadFile(filePathFromProject);
  }, [filePathFromProject]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!reloadKey || !filePathFromProject) return;
    loadFile(filePathFromProject);
  }, [reloadKey]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { onDirtyChange?.(isDirty); }, [isDirty]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { onRegisterSave?.(handleSave); }, [handleSave]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!filePath || !onWindParamsChange) return;
    const btsBasename = p.FileName_BTS
      ? p.FileName_BTS.replace(/\\/g, "/").split("/").pop()
      : "";
    onWindParamsChange(p.WindType, String(p.HWindSpeed), btsBasename);
  }, [p.WindType, p.HWindSpeed, p.FileName_BTS]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── BTS scanning ───────────────────────────────────────────────────────────
  const scanBts = useCallback(async () => {
    if (!project) return;
    setScanning(true);
    try {
      const raw = await invoke("sidecar_call", {
        payload: JSON.stringify({ cmd: "list_bts_files", working_dir: project.windDir ?? project.workingDir }),
      });
      const res = JSON.parse(raw);
      if (res.ok) setBtsFiles(res.files);
    } catch {}
    setScanning(false);
  }, [project]);

  useEffect(() => { if (project) scanBts(); }, [project, scanBts]);

  const browseBts = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "TurbSim wind field", extensions: ["bts"] }] });
      if (f) setP(prev => ({ ...prev, FileName_BTS: f }));
    } catch {}
  };

  const browseWnd = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "Uniform wind file", extensions: ["wnd"] }] });
      if (f) setP(prev => ({ ...prev, Filename_Uni: f }));
    } catch {}
  };

  const browseBladed = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "Bladed wind file", extensions: ["wnd", "sum"] }] });
      if (f) setP(prev => ({ ...prev, FilenameRoot: f.replace(/\.(wnd|sum)$/i, "") }));
    } catch {}
  };

  const browseHawc = async (key, exts) => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "HAWC2 wind component", extensions: exts }] });
      if (f) setP(prev => ({ ...prev, [key]: f }));
    } catch {}
  };

  const browseUserFile = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "User DLL", extensions: ["dll", "so", "dylib"] }] });
      if (f) setP(prev => ({ ...prev, UserFile: f }));
    } catch {}
  };

  // ── Derived ────────────────────────────────────────────────────────────────
  const wt          = WIND_TYPES.find(t => t.value === p.WindType);
  const displayPath = filePath
    ? filePath.replace(/\\/g, "/").split("/").slice(-3).join("/")
    : "";

  const stats = [
    { k: "Type",       v: wt?.label || "—" },
    { k: "Hub height", v: `${p.WindVziList} m` },
    ...(p.WindType === 1 ? [
      { k: "Wind speed", v: `${Number(p.HWindSpeed).toFixed(1)} m/s` },
      { k: "Shear α",   v: String(p.PLexp) },
      { k: "Prop. dir", v: `${p.PropagationDir}°` },
    ] : p.WindType === 2 ? [
      { k: "Ref height", v: `${p.RefHt_Uni} m` },
      { k: "Ref length", v: `${p.RefLength} m` },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
    ] : p.WindType === 6 ? [
      { k: "DLL file",   v: p.UserFile !== "none" ? p.UserFile.split(/[\\/]/).pop() : "—" },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
    ] : p.WindType === 4 || p.WindType === 7 ? [
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
      { k: "Tower file", v: p.TowerFile ? "Yes" : "No" },
    ] : p.WindType === 5 ? [
      { k: "Grid",       v: `${p.nx}×${p.ny}×${p.nz}` },
      { k: "U ref",      v: `${p.URef} m/s` },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
    ] : [
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
    ]),
    { k: "VelInterp",  v: p.VelInterpCubic ? "Cubic" : "Linear" },
    { k: "LIDAR",      v: p.SensorType === 0 ? "Off" : `Type ${p.SensorType}` },
  ];

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className={s.panel}>

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className={s.header}>
        <Cloud size={14} strokeWidth={1.8} className={s.headerIcon} />
        <span className={s.title}>InflowWind</span>
        <span className={s.desc}>inflow conditions</span>
        <span className={s.badge}>v3.01</span>
        <div style={{ flex: 1 }} />
        <button className={`${s.headerBtn} ${s.headerBtnPrimary}`} onClick={handleOpen} type="button">
          <FolderOpen size={12} strokeWidth={1.8} /> Open .dat
        </button>
        <button className={s.headerBtn} onClick={handleViewRaw} title="Preview .dat content" type="button">
          <Eye size={12} strokeWidth={1.8} /> View .dat
        </button>
      </div>

      {/* ── File bar ───────────────────────────────────────────────────────── */}
      <div className={[s.fileBar, filePath ? s.fileBarLoaded : ""].join(" ")}>
        <span className={`${s.filePath} ${filePath ? s.filePathSet : ""}`}>
          {filePath
            ? (displayPath || filePath.split("/").pop())
            : "No file open — click Open .dat to load an existing file"}
        </span>
        <span className={s.dirtyDot} style={{ opacity: isDirty ? 1 : 0 }} title="Unsaved changes" />
        <button
          className={[s.saveBtn, (!isDirty || simRunning) ? s.saveBtnInactive : ""].join(" ")}
          onClick={(!isDirty || simRunning) ? undefined : handleSave}
          type="button"
          title={simRunning ? "OpenFAST is running — save blocked" : "Save (⌘S)"}
        >
          <Save size={11} strokeWidth={2} /> Save
        </button>
      </div>

      {/* ── Sim running banner ─────────────────────────────────────────────── */}
      {simRunning && (
        <div style={{
          display: "flex", alignItems: "center", gap: 8,
          padding: "7px 18px",
          background: "rgba(217,119,6,0.10)",
          borderBottom: "0.5px solid rgba(217,119,6,0.28)",
          flexShrink: 0,
        }}>
          <span style={{ fontSize: 13 }}>⚠</span>
          <span style={{ fontSize: 12, fontWeight: 500, color: "#92400E" }}>
            OpenFAST is running — saving is disabled to protect the active simulation
          </span>
        </div>
      )}

      {/* ── Raw file modal ─────────────────────────────────────────────────── */}
      {showRaw && rawContent && (
        <RawFileModal
          content={rawContent}
          filename={filePath ? filePath.split("/").pop() : "InflowWind.dat"}
          fromDisk={!!filePath}
          hasDirtyWarning={isDirty}
          filePath={filePath}
          onSaved={(newContent) => { setRawContent(newContent); loadFile(filePath); }}
          onClose={() => setShowRaw(false)}
        />
      )}

      {/* ── Tab bar ────────────────────────────────────────────────────────── */}
      <div className={s.tabBar}>
        {TABS.map(t => (
          <button
            key={t.id}
            type="button"
            className={`${s.tab} ${tab === t.id ? s.tabActive : ""}`}
            onClick={() => {
              const oldIdx = TABS.findIndex(x => x.id === tab);
              const newIdx = TABS.findIndex(x => x.id === t.id);
              tabDirRef.current = newIdx >= oldIdx ? 1 : -1;
              setTab(t.id);
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* ── Missing-fields banner ──────────────────────────────────────────── */}
      {missingFields.length > 0 && (
        <div className={s.absentBanner}>
          <AlertTriangle size={12} style={{ flexShrink: 0, marginTop: 1 }} />
          <span>
            <strong>{missingFields.length} parameter{missingFields.length > 1 ? "s" : ""}</strong>
            {" "}not found in this file — showing model defaults.{" "}
            <span className={s.absentList}>
              {missingFields.slice(0, 10).map((f, i) => (
                <span key={f}>
                  {i > 0 && <span style={{ opacity: 0.5 }}> · </span>}
                  {FIELD_TAB[f] ? (
                    <button className={s.absentFieldBtn} onClick={() => setTab(FIELD_TAB[f])} title={`Jump to ${FIELD_TAB[f]} tab`}>
                      {f}
                    </button>
                  ) : f}
                </span>
              ))}
              {missingFields.length > 10 && <span style={{ opacity: 0.5 }}> · +{missingFields.length - 10} more</span>}
            </span>
          </span>
        </div>
      )}

      {/* ── Content row ────────────────────────────────────────────────────── */}
      <div className={s.contentRow}>

        <div className={s.formArea}>
          <MissingCtx.Provider value={new Set(missingFields)}>

            {/* ══ SOURCE TAB ══════════════════════════════════════════════════ */}
            {tab === "source" && (
              <div className={`${s.form} ${s.tabEnterFirst}`}>

                <div className={s.callout}>
                  Wind source settings shown below depend on the selected wind type. Only parameters for the active type are written to the .dat file.
                </div>

                <p className={s.sectionHead}>
                  Wind Source
                  <InfoPopover content={INFO.WindType} accentColor={ACCENT} />
                </p>

                <div className={s.typeBar}>
                  {WIND_TYPES.map(t => (
                    <button
                      key={t.value}
                      type="button"
                      className={`${s.typeBtn} ${p.WindType === t.value ? s.typeBtnActive : ""}`}
                      onClick={() => setP(prev => ({ ...prev, WindType: t.value }))}
                    >
                      {t.label}
                    </button>
                  ))}
                </div>
                <p key={p.WindType} className={s.typeDesc}>{wt?.desc}</p>

                {/* Steady ────────────────────────────────────────────────── */}
                {p.WindType === 1 && (
                  <div className={s.sourceCard}>
                    <div className={s.grid2}>
                      <Field label="Wind speed (HWindSpeed)" unit="m/s" info={INFO.HWindSpeed} fieldKey="HWindSpeed">
                        <input className={s.inp} type="number" value={p.HWindSpeed}
                          onChange={setNum("HWindSpeed")} step="0.5" />
                      </Field>
                      <Field label="Reference height (RefHt)" unit="m" info={INFO.RefHt} fieldKey="RefHt">
                        <input className={s.inp} type="number" value={p.RefHt}
                          onChange={setNum("RefHt")} />
                      </Field>
                      <Field label="Power law exponent α (PLexp)" info={INFO.PLexp} fieldKey="PLexp">
                        <input className={s.inp} type="number" value={p.PLexp}
                          onChange={setNum("PLexp")} step="0.01" />
                      </Field>
                    </div>
                  </div>
                )}

                {/* Uniform ───────────────────────────────────────────────── */}
                {p.WindType === 2 && (
                  <div className={s.sourceCard}>
                    <Field label="Wind file (Filename_Uni)" info={INFO.Filename_Uni} fieldKey="Filename_Uni">
                      <div className={s.fileRow}>
                        <input className={s.inp} type="text" value={p.Filename_Uni === "none" ? "" : p.Filename_Uni}
                          onChange={e => setP(prev => ({ ...prev, Filename_Uni: e.target.value || "none" }))}
                          placeholder="Path to .wnd file…" />
                        <button className={s.browseBtn} onClick={browseWnd} title="Browse" type="button">
                          <FolderOpen size={13} strokeWidth={1.8} />
                        </button>
                      </div>
                    </Field>
                    <div className={s.grid2} style={{ marginTop: 12 }}>
                      <Field label="Reference height (RefHt_Uni)" unit="m" info={INFO.RefHt_Uni} fieldKey="RefHt_Uni">
                        <input className={s.inp} type="number" value={p.RefHt_Uni} onChange={setNum("RefHt_Uni")} />
                      </Field>
                      <Field label="Reference length (RefLength)" unit="m" info={INFO.RefLength} fieldKey="RefLength">
                        <input className={s.inp} type="number" value={p.RefLength} onChange={setNum("RefLength")} />
                      </Field>
                    </div>
                  </div>
                )}

                {/* TurbSim BTS ───────────────────────────────────────────── */}
                {p.WindType === 3 && (
                  <div className={s.sourceCard}>
                    <Field label="Wind field file (FileName_BTS)" info={INFO.FileName_BTS} fieldKey="FileName_BTS">
                      <div className={s.fileRow}>
                        <input className={s.inp} type="text" value={p.FileName_BTS}
                          onChange={e => setP(prev => ({ ...prev, FileName_BTS: e.target.value }))}
                          placeholder="Path to .bts file…" />
                        <button className={s.browseBtn} onClick={browseBts} title="Browse" type="button">
                          <FolderOpen size={13} strokeWidth={1.8} />
                        </button>
                      </div>
                    </Field>
                    {project && (
                      <div className={s.scanRow}>
                        <button className={s.scanBtn} onClick={scanBts} disabled={scanning} type="button">
                          <RefreshCw size={11} strokeWidth={2} className={scanning ? s.spinning : ""} />
                          {scanning ? "Scanning…" : "Scan project"}
                        </button>
                        {btsFiles.length > 0 ? (
                          <div className={s.btsPickerWrap}>
                            <select className={s.btsPicker} value={p.FileName_BTS}
                              onChange={e => e.target.value && setP(prev => ({ ...prev, FileName_BTS: e.target.value }))}>
                              <option value="">— {btsFiles.length} .bts files found —</option>
                              {btsFiles.map(f => (
                                <option key={f.path} value={f.path}>{f.rel}</option>
                              ))}
                            </select>
                            <ChevronDown size={12} className={s.btsChevron} />
                          </div>
                        ) : !scanning && (
                          <span className={s.noBts}>No .bts files — run TurbSim or DLC Batch first</span>
                        )}
                      </div>
                    )}
                  </div>
                )}

                {/* Bladed FF (types 4 & 7) ───────────────────────────────── */}
                {(p.WindType === 4 || p.WindType === 7) && (
                  <div className={s.sourceCard}>
                    <Field
                      label={p.WindType === 4 ? "Root filename — .wnd/.sum (FilenameRoot)" : "Scaling values file (FilenameRoot)"}
                      info={INFO.FilenameRoot}
                      fieldKey="FilenameRoot"
                    >
                      <div className={s.fileRow}>
                        <input className={s.inp} type="text"
                          value={p.FilenameRoot === "none" ? "" : p.FilenameRoot}
                          onChange={e => setP(prev => ({ ...prev, FilenameRoot: e.target.value || "none" }))}
                          placeholder={p.WindType === 4 ? "Root path (no extension)…" : "Path to scaling values file…"} />
                        <button className={s.browseBtn} onClick={browseBladed} title="Browse" type="button">
                          <FolderOpen size={13} strokeWidth={1.8} />
                        </button>
                      </div>
                    </Field>
                    {p.WindType === 4 && (
                      <div className={s.field} style={{ marginTop: 10 }}>
                        <Field label="Tower file (TowerFile)" info={INFO.TowerFile} fieldKey="TowerFile">
                          <Toggle
                            value={p.TowerFile}
                            onChange={v => setP(prev => ({ ...prev, TowerFile: v }))}
                            label="Include tower wind data (.twr)"
                          />
                        </Field>
                      </div>
                    )}
                  </div>
                )}

                {/* HAWC2 (type 5) ────────────────────────────────────────── */}
                {p.WindType === 5 && (
                  <div className={s.sourceCard}>
                    {[
                      { key: "FileName_u", label: "u-component (FileName_u)", info: INFO.FileName_u },
                      { key: "FileName_v", label: "v-component (FileName_v)", info: INFO.FileName_v },
                      { key: "FileName_w", label: "w-component (FileName_w)", info: INFO.FileName_w },
                    ].map(({ key, label, info }) => (
                      <Field key={key} label={label} info={info} fieldKey={key}>
                        <div className={s.fileRow}>
                          <input className={s.inp} type="text"
                            value={p[key] === "none" ? "" : p[key]}
                            onChange={e => setP(prev => ({ ...prev, [key]: e.target.value || "none" }))}
                            placeholder="Path to .bin file…" />
                          <button className={s.browseBtn} onClick={() => browseHawc(key, ["bin"])} title="Browse" type="button">
                            <FolderOpen size={13} strokeWidth={1.8} />
                          </button>
                        </div>
                      </Field>
                    ))}

                    <p className={s.sectionHead} style={{ marginTop: 14 }}>Wind Box Grid</p>
                    <div className={s.grid3}>
                      {[
                        { k: "nx", label: "nx (x pts)",   info: INFO.nx },
                        { k: "ny", label: "ny (y pts)",   info: INFO.ny },
                        { k: "nz", label: "nz (z pts)",   info: INFO.nz },
                      ].map(({ k, label, info }) => (
                        <Field key={k} label={label} info={info} fieldKey={k}>
                          <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} min="1" step="1" />
                        </Field>
                      ))}
                      {[
                        { k: "dx", label: "dx", unit: "m", info: INFO.dx },
                        { k: "dy", label: "dy", unit: "m", info: INFO.dy },
                        { k: "dz", label: "dz", unit: "m", info: INFO.dz },
                      ].map(({ k, label, unit, info }) => (
                        <Field key={k} label={label} unit={unit} info={info} fieldKey={k}>
                          <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} step="0.5" />
                        </Field>
                      ))}
                      <Field label="RefHt_Hawc" unit="m" info={INFO.RefHt_Hawc} fieldKey="RefHt_Hawc">
                        <input className={s.inp} type="number" value={p.RefHt_Hawc} onChange={setNum("RefHt_Hawc")} />
                      </Field>
                      <Field label="XOffset" unit="m" info={INFO.XOffset} fieldKey="XOffset">
                        <input className={s.inp} type="number" value={p.XOffset} onChange={setNum("XOffset")} />
                      </Field>
                    </div>

                    <p className={s.sectionHead} style={{ marginTop: 14 }}>
                      Turbulence Scaling
                      <InfoPopover content={INFO.ScaleMethod} accentColor={ACCENT} />
                    </p>
                    <Field label="Scale method (ScaleMethod)" info={INFO.ScaleMethod} fieldKey="ScaleMethod">
                      <select className={s.inp} value={p.ScaleMethod} onChange={setNum("ScaleMethod")}>
                        <option value={0}>0 — None (raw values)</option>
                        <option value={1}>1 — Direct scale factors (SF)</option>
                        <option value={2}>2 — Target standard deviation (Sigma)</option>
                      </select>
                    </Field>
                    {p.ScaleMethod === 1 && (
                      <div className={s.grid3} style={{ marginTop: 8 }}>
                        {["SFx","SFy","SFz"].map(k => (
                          <Field key={k} label={k} fieldKey={k}>
                            <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} step="0.1" />
                          </Field>
                        ))}
                      </div>
                    )}
                    {p.ScaleMethod === 2 && (
                      <div className={s.grid3} style={{ marginTop: 8 }}>
                        {[
                          { k: "SigmaFx", label: "σFx" },
                          { k: "SigmaFy", label: "σFy" },
                          { k: "SigmaFz", label: "σFz" },
                        ].map(({ k, label }) => (
                          <Field key={k} label={label} unit="m/s" fieldKey={k}>
                            <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} step="0.1" />
                          </Field>
                        ))}
                      </div>
                    )}

                    <p className={s.sectionHead} style={{ marginTop: 14 }}>
                      Mean Wind Profile
                      <InfoPopover content={INFO.WindProfile} accentColor={ACCENT} />
                    </p>
                    <div className={s.grid2}>
                      <Field label="U ref (URef)" unit="m/s" info={INFO.URef} fieldKey="URef">
                        <input className={s.inp} type="number" value={p.URef} onChange={setNum("URef")} step="0.5" />
                      </Field>
                      <Field label="Profile type (WindProfile)" info={INFO.WindProfile} fieldKey="WindProfile">
                        <select className={s.inp} value={p.WindProfile} onChange={setNum("WindProfile")}>
                          <option value={0}>0 — Constant</option>
                          <option value={1}>1 — Logarithmic</option>
                          <option value={2}>2 — Power law</option>
                        </select>
                      </Field>
                      {p.WindProfile === 2 && (
                        <Field label="PLExp_Hawc (α)" info={INFO.PLExp_Hawc} fieldKey="PLExp_Hawc">
                          <input className={s.inp} type="number" value={p.PLExp_Hawc} onChange={setNum("PLExp_Hawc")} step="0.01" />
                        </Field>
                      )}
                      {p.WindProfile === 1 && (
                        <Field label="Z0" unit="m" info={INFO.Z0} fieldKey="Z0">
                          <input className={s.inp} type="number" value={p.Z0} onChange={setNum("Z0")} step="0.001" />
                        </Field>
                      )}
                    </div>
                  </div>
                )}

                {/* User DLL (type 6) ──────────────────────────────────────── */}
                {p.WindType === 6 && (
                  <div className={s.sourceCard}>
                    <Field label="DLL wind file (UserFile)" info={INFO.UserFile} fieldKey="UserFile">
                      <div className={s.fileRow}>
                        <input className={s.inp} type="text"
                          value={p.UserFile === "none" ? "" : p.UserFile}
                          onChange={e => setP(prev => ({ ...prev, UserFile: e.target.value || "none" }))}
                          placeholder="Path to user-defined DLL…" />
                        <button className={s.browseBtn} onClick={browseUserFile} title="Browse" type="button">
                          <FolderOpen size={13} strokeWidth={1.8} />
                        </button>
                      </div>
                    </Field>
                    <p className={s.hint} style={{ marginTop: 8 }}>
                      WindType=6 requires a DLL implementing the InflowWind user-defined wind interface.
                      Configure DLL-specific parameters directly in the .dat file.
                    </p>
                  </div>
                )}

                {/* VelInterpCubic — below sourceCard, disabled for Steady */}
                <div className={s.field} style={{ marginTop: 10 }}>
                  <Field
                    label="Cubic time interpolation (VelInterpCubic)"
                    info={INFO.VelInterpCubic}
                    fieldKey="VelInterpCubic"
                    disabledHint={p.WindType === 1 ? "Switch to a time-varying wind type (e.g. TurbSim BTS) to enable cubic interpolation" : undefined}
                  >
                    <Toggle
                      value={p.VelInterpCubic}
                      onChange={v => setP(prev => ({ ...prev, VelInterpCubic: v }))}
                      label="VelInterpCubic"
                      disabled={p.WindType === 1}
                      note={p.WindType === 1 ? "not used for Steady" : undefined}
                    />
                  </Field>
                </div>

                {/* Generate section (only when no file is open) */}
                {!filePath && (
                  <>
                    <p className={s.sectionHead} style={{ marginTop: 20 }}>Create file</p>
                    <div className={s.outputRow}>
                      <div className={s.autoNameBox}>
                        <span className={s.autoNameLabel}>Auto-name</span>
                        <span className={s.autoNameVal}>{autoName}</span>
                      </div>
                      <label className={s.field} style={{ marginTop: 8 }}>
                        <span className={s.fieldLabel}>
                          Custom filename <span className={s.unit}>(optional)</span>
                        </span>
                        <input className={s.inp} type="text" value={customDatName}
                          placeholder={autoName}
                          onChange={e => setCustomDatName(e.target.value)} />
                      </label>
                      {project && (
                        <span className={s.hint} style={{ marginTop: 4 }}>
                          → {project.modelDir ?? project.workingDir}/{effectiveDatName}
                        </span>
                      )}
                    </div>
                    <div className={s.actionRow}>
                      <button
                        className={s.writeBtn}
                        onClick={handleGenerate}
                        disabled={generating || !project}
                        title={!project ? "Select a project folder first" : undefined}
                        type="button"
                      >
                        {generating ? "Writing…" : `Generate ${effectiveDatName}`}
                      </button>
                    </div>
                  </>
                )}
              </div>
            )}

            {/* ══ FLOW TAB ════════════════════════════════════════════════════ */}
            {tab === "flow" && (
              <div className={`${s.form} ${s.tabEnter}`} style={{ "--tab-dir": tabDirRef.current }}>

                <p className={s.sectionHead}>Flow Direction</p>
                <div className={s.grid2}>
                  <Field label="Propagation direction (PropagationDir)" unit="°"
                    info={INFO.PropagationDir} fieldKey="PropagationDir"
                    hint="Met. convention — 0° = wind from North">
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.PropagationDir}
                        onChange={setNum("PropagationDir")} step="1" />
                      <span className={s.unit}>°</span>
                    </div>
                  </Field>
                  <Field label="Upflow angle (VFlowAng)" unit="°"
                    info={INFO.VFlowAng} fieldKey="VFlowAng"
                    hint="Vertical flow inclination">
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.VFlowAng}
                        onChange={setNum("VFlowAng")} step="0.5" />
                      <span className={s.unit}>°</span>
                    </div>
                  </Field>
                </div>

                <p className={s.sectionHead} style={{ marginTop: 10 }}>Velocity Output Point</p>
                <div className={s.callout} style={{ marginBottom: 16 }}>
                  InflowWind evaluates the wind velocity at NWindVel user-specified points and writes
                  it to the OpenFAST output channels. Set Z to match ElastoDyn HubHt for correct hub-height wind speed.
                </div>
                <div className={s.grid2}>
                  <Field label="Number of output points (NWindVel)" info={INFO.NWindVel} fieldKey="NWindVel">
                    <input className={s.inp} type="number" value={p.NWindVel}
                      onChange={setNum("NWindVel")} min="0" max="9" step="1" />
                  </Field>
                </div>
                <div className={s.grid3}>
                  <Field label="X position (WindVxiList)" unit="m" info={INFO.WindVxiList} fieldKey="WindVxiList"
                    hint="Streamwise (0 = tower CL)">
                    <input className={s.inp} type="number" value={p.WindVxiList}
                      onChange={setNum("WindVxiList")} step="1" />
                  </Field>
                  <Field label="Y position (WindVyiList)" unit="m" info={INFO.WindVyiList} fieldKey="WindVyiList"
                    hint="Lateral (0 = tower CL)">
                    <input className={s.inp} type="number" value={p.WindVyiList}
                      onChange={setNum("WindVyiList")} step="1" />
                  </Field>
                  <Field label="Z / Hub height (WindVziList)" unit="m" info={INFO.WindVziList} fieldKey="WindVziList"
                    hint="Match ElastoDyn HubHt">
                    <input className={s.inp} type="number" value={p.WindVziList}
                      onChange={setNum("WindVziList")} step="1" />
                  </Field>
                </div>
              </div>
            )}

            {/* ══ LIDAR TAB ═══════════════════════════════════════════════════ */}
            {tab === "lidar" && (
              <div className={`${s.form} ${s.tabEnter}`} style={{ "--tab-dir": tabDirRef.current }}>

                <div className={s.callout}>
                  Lidar simulation is inactive when SensorType=0 (default). Set SensorType to 1 (pulsed)
                  or 2 (continuous wave) to enable the lidar preview wind measurement model.
                </div>

                <p className={s.sectionHead}>Sensor</p>
                <div className={s.grid2}>
                  <Field label="Sensor type (SensorType)" info={INFO.SensorType} fieldKey="SensorType">
                    <select className={s.inp} value={p.SensorType} onChange={setNum("SensorType")}>
                      <option value={0}>0 — None (disabled)</option>
                      <option value={1}>1 — Pulsed lidar</option>
                      <option value={2}>2 — Continuous wave</option>
                    </select>
                  </Field>
                  <Field
                    label="Number of beams (NumBeam)" info={INFO.NumBeam} fieldKey="NumBeam"
                    hint="0–5 beams"
                    disabledHint={p.SensorType === 0 ? "Set SensorType to 1 (Pulsed) or 2 (CW) to enable lidar parameters" : undefined}
                  >
                    <input className={s.inp} type="number" value={p.NumBeam}
                      onChange={setNum("NumBeam")} min="0" max="5" step="1"
                      disabled={p.SensorType === 0} />
                  </Field>
                </div>

                <Collapsible title="Pulse gates (SensorType=1 only)" defaultOpen={p.SensorType === 1}>
                  <div className={s.grid2}>
                    <Field label="Number of gates (NumPulseGate)" info={INFO.NumPulseGate} fieldKey="NumPulseGate">
                      <input className={s.inp} type="number" value={p.NumPulseGate}
                        onChange={setNum("NumPulseGate")} min="0" step="1" />
                    </Field>
                    <Field label="Gate spacing (PulseSpacing)" unit="m" info={INFO.PulseSpacing} fieldKey="PulseSpacing">
                      <input className={s.inp} type="number" value={p.PulseSpacing}
                        onChange={setNum("PulseSpacing")} step="1" />
                    </Field>
                  </div>
                </Collapsible>

                <p className={s.sectionHead}>Focal Point</p>
                <div className={s.grid3}>
                  <Field
                    label="X distance (FocalDistanceX)" unit="m" info={INFO.FocalDistanceX} fieldKey="FocalDistanceX"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to enable focal point settings" : undefined}
                  >
                    <input className={s.inp} type="number" value={p.FocalDistanceX}
                      onChange={setNum("FocalDistanceX")} step="10"
                      disabled={p.SensorType === 0} />
                  </Field>
                  <Field
                    label="Y distance (FocalDistanceY)" unit="m" info={INFO.FocalDistanceY} fieldKey="FocalDistanceY"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to enable focal point settings" : undefined}
                  >
                    <input className={s.inp} type="number" value={p.FocalDistanceY}
                      onChange={setNum("FocalDistanceY")} step="1"
                      disabled={p.SensorType === 0} />
                  </Field>
                  <Field
                    label="Z distance (FocalDistanceZ)" unit="m" info={INFO.FocalDistanceZ} fieldKey="FocalDistanceZ"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to enable focal point settings" : undefined}
                  >
                    <input className={s.inp} type="number" value={p.FocalDistanceZ}
                      onChange={setNum("FocalDistanceZ")} step="1"
                      disabled={p.SensorType === 0} />
                  </Field>
                </div>

                <p className={s.sectionHead}>Position & Timing</p>
                <div className={s.grid2}>
                  <Field
                    label="Apex offset pos. (RotorApexOffsetPos)" unit="m m m"
                    info={INFO.RotorApexOffsetPos} fieldKey="RotorApexOffsetPos"
                    hint="Three space-separated values: X Y Z"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to configure lidar position" : undefined}
                  >
                    <input className={s.inp} type="text" value={p.RotorApexOffsetPos}
                      onChange={e => setP(prev => ({ ...prev, RotorApexOffsetPos: e.target.value }))}
                      placeholder="0.0 0.0 0.0"
                      disabled={p.SensorType === 0} />
                  </Field>
                  <Field
                    label="Measurement interval (MeasurementInterval)" unit="s"
                    info={INFO.MeasurementInterval} fieldKey="MeasurementInterval"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to configure measurement timing" : undefined}
                  >
                    <input className={s.inp} type="number" value={p.MeasurementInterval}
                      onChange={setNum("MeasurementInterval")} step="0.05"
                      disabled={p.SensorType === 0} />
                  </Field>
                  <Field
                    label="Reference speed (URefLid)" unit="m/s" info={INFO.URefLid} fieldKey="URefLid"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to configure lidar reference speed" : undefined}
                  >
                    <input className={s.inp} type="number" value={p.URefLid}
                      onChange={setNum("URefLid")} step="0.5"
                      disabled={p.SensorType === 0} />
                  </Field>
                  <Field
                    label="Hub motion influence (ConsiderHubMotion)"
                    info={INFO.ConsiderHubMotion} fieldKey="ConsiderHubMotion"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to configure hub motion" : undefined}
                  >
                    <select className={s.inp} value={p.ConsiderHubMotion}
                      onChange={setNum("ConsiderHubMotion")}
                      disabled={p.SensorType === 0}>
                      <option value={0}>0 — Ignore hub motion</option>
                      <option value={1}>1 — Include hub motion</option>
                    </select>
                  </Field>
                </div>

                <div className={s.field}>
                  <Field
                    label="Return radial velocity (LidRadialVel)" info={INFO.LidRadialVel} fieldKey="LidRadialVel"
                    disabledHint={p.SensorType === 0 ? "Set SensorType > 0 to configure lidar output mode" : undefined}
                  >
                    <Toggle
                      value={p.LidRadialVel}
                      onChange={v => setP(prev => ({ ...prev, LidRadialVel: v }))}
                      label="LidRadialVel — report line-of-sight component"
                      disabled={p.SensorType === 0}
                    />
                  </Field>
                </div>
              </div>
            )}

            {/* ══ OUTPUT TAB ══════════════════════════════════════════════════ */}
            {tab === "output" && (
              <div className={`${s.form} ${s.tabEnter}`} style={{ "--tab-dir": tabDirRef.current }}>

                <p className={s.sectionHead}>Summary & Debug</p>
                <div className={s.toggleGrid}>
                  <Field label="Summary file (SumPrint)" info={INFO.SumPrint} fieldKey="SumPrint">
                    <Toggle
                      value={p.SumPrint}
                      onChange={v => setP(prev => ({ ...prev, SumPrint: v }))}
                      label="Write .IfW.sum summary file"
                    />
                  </Field>
                  <Field label="Echo inputs (Echo)" info={INFO.Echo} fieldKey="Echo">
                    <Toggle
                      value={p.Echo}
                      onChange={v => setP(prev => ({ ...prev, Echo: v }))}
                      label="Write .IfW.echo debug file"
                    />
                  </Field>
                </div>

                <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 10, marginBottom: 4 }}>
                  <p className={s.sectionHead} style={{ margin: 0 }}>
                    Output Channels (OutList)
                    <InfoPopover content={INFO.OutList} accentColor={ACCENT} />
                  </p>
                  <div style={{ flex: 1 }} />
                  <button
                    className={s.pickVarsBtn}
                    type="button"
                    onClick={() => setShowOutVarModal(true)}
                  >
                    <List size={11} strokeWidth={2} />
                    Pick variables
                  </button>
                </div>
                <p className={s.hint} style={{ marginBottom: 8 }}>
                  One channel name per line. Quotes are optional — added automatically on save.
                  Common channels: Wind1VelX · Wind1VelY · Wind1VelZ
                </p>
                <textarea
                  className={s.outListArea}
                  value={p.OutList}
                  onChange={e => setP(prev => ({ ...prev, OutList: e.target.value }))}
                  spellCheck={false}
                  rows={8}
                />

                {showOutVarModal && (
                  <OutVarModal
                    current={p.OutList}
                    onClose={() => setShowOutVarModal(false)}
                    onApply={outList => setP(prev => ({ ...prev, OutList: outList }))}
                  />
                )}
              </div>
            )}

          </MissingCtx.Provider>
        </div>

        {/* ── Stats sidebar ──────────────────────────────────────────────────── */}
        <div className={s.statsPanel}>
          <span className={s.statsLabel}>Quick stats</span>
          <div className={s.turbineWrap}>
            <WindVizSVG windType={p.WindType} windSpeed={p.HWindSpeed} plExp={p.PLexp} />
          </div>
          <div className={s.statsGrid}>
            {stats.map(({ k, v }) => (
              <div key={k} className={s.statCard}>
                <span className={s.statKey}>{k}</span>
                <span className={s.statVal}>{v}</span>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
