import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open as openDialog } from "@tauri-apps/plugin-dialog";
import { Cloud, FolderOpen, RefreshCw, Eye, Save, ChevronDown } from "lucide-react";
import InfoPopover from "../InfoPopover";
import RawFileModal from "../RawFileModal";
import s from "./InflowWindPanel.module.css";

const ACCENT = "#378ADD";

// ── Field info ────────────────────────────────────────────────────────────────
const INFO = {
  WindType: {
    param: "WindType",
    desc:  "Selects the wind input model. Type 3 (TurbSim BTS) is the standard choice when driving OpenFAST with stochastic IEC wind fields generated by TurbSim.",
    range: "1–7",
    default: "3",
  },
  PropagationDir: {
    param: "PropagationDir",
    desc:  "Direction the wind is travelling, using meteorological convention: 0° = wind blowing from North, 90° = wind blowing from East.",
    range: "−180° to 180°",
    default: "0°",
    unit: "degrees",
  },
  VFlowAng: {
    param: "VFlowAng",
    desc:  "Vertical inclination of the mean flow. Positive = upslope flow. Typically 0° for flat terrain; may be non-zero for complex terrain studies.",
    range: "−45° to 45°",
    default: "0°",
    unit: "degrees",
  },
  WindVziList: {
    param: "WindVziList",
    desc:  "Height at which InflowWind writes out point wind velocity to the OpenFAST output file. Should match HubHt in ElastoDyn so hub-height wind speed appears in results.",
    unit: "m",
    note: "Tip: set this equal to the ElastoDyn HubHt parameter.",
  },
  HWindSpeed: {
    param: "HWindSpeed",
    desc:  "Mean horizontal wind speed at the reference height. Used only for WindType=1 (Steady). AeroDyn will see this speed at every grid point.",
    unit: "m/s",
    default: "12.0",
  },
  RefHt: {
    param: "RefHt",
    desc:  "Height at which HWindSpeed is defined. The power law profile U(z) = HWindSpeed × (z/RefHt)^PLexp is applied above and below this height.",
    unit: "m",
    default: "hub height",
  },
  PLexp: {
    param: "PLexp",
    desc:  "Wind shear exponent α in the power law profile U(z) ∝ z^α. IEC 61400-1 default is 0.2 for land-based turbines; offshore typically 0.14.",
    range: "0.05–0.40",
    default: "0.2",
    note: "IEC 61400-1 Ed.3 §6.3 specifies α = 0.2 unless site-specific data is available.",
  },
  FileName_BTS: {
    param: "FileName_BTS",
    desc:  "Path to the TurbSim binary full-field wind file (.bts). Must match the grid dimensions (HubHt, GridHeight, GridWidth) used in the OpenFAST model.",
    note:  "Use 'Scan project' to auto-discover .bts files generated by TurbSim or DLC Batch.",
  },
  SumPrint: {
    param: "SumPrint",
    desc:  "When True, InflowWind writes a <RootName>.IfW.sum summary file with mean wind speed, turbulence intensity, and power spectral density at the output point.",
    default: "False",
  },
  Filename_Uni: {
    param: "Filename_Uni",
    desc:  "Path to the Uniform wind time-series file (.wnd). Each row contains: Time, HorSpd, WindDir, VertSpd, HorShr, VerShr, LnVShr, GstSpd.",
    note:  "Uniform wind files can be created manually or with the InflowWind pre-processor.",
  },
  RefHt_Uni: {
    param: "RefHt_Uni",
    desc:  "Height at which HorSpd in the .wnd file is defined. Wind profile shear is applied relative to this height.",
    unit:  "m",
  },
  RefLength: {
    param: "RefLength",
    desc:  "Reference length used to non-dimensionalise the horizontal and vertical shear columns in the Uniform wind file.",
    unit:  "m",
  },
  VelInterpCubic: {
    param: "VelInterpCubic",
    desc:  "When True, uses cubic (rather than linear) interpolation in time for the wind velocity lookup. Cubic is smoother but costs ~30% more CPU. Not used for WindType=1 (Steady).",
    default: "False",
  },
  FilenameRoot: {
    param: "FilenameRoot",
    desc:  "Root name of the Bladed-style wind files. For WindType=4 InflowWind appends '.wnd' (binary) and '.sum' (header). For WindType=7 this is the name of the file containing wind scaling values.",
  },
  TowerFile: {
    param: "TowerFile",
    desc:  "When True, InflowWind reads a tower wind file (<RootName>.twr) that provides wind speed at tower stations for aerodynamic tower loading. Ignored for WindType=7.",
    default: "False",
  },
  FileName_u: {
    param: "FileName_u",
    desc:  "HAWC2 binary file containing the longitudinal (u) component of the fluctuating wind field.",
  },
  nx: {
    param: "nx",
    desc:  "Number of grid points in the x (streamwise) direction in the HAWC2 wind box.",
  },
  ScaleMethod: {
    param: "ScaleMethod",
    desc:  "Turbulence scaling method for HAWC2 files: 0 = no scaling (use raw values), 1 = direct scale factors (SFx/SFy/SFz), 2 = scale to achieve target standard deviation (SigmaFx/SigmaFy/SigmaFz).",
    range: "0, 1, 2",
    default: "1",
  },
  URef: {
    param: "URef",
    desc:  "Mean u-component wind speed at the HAWC2 reference height. Added to the fluctuating field to produce the total wind field.",
    unit:  "m/s",
  },
  WindProfile: {
    param: "WindProfile",
    desc:  "Mean wind profile type for the HAWC2 mean wind: 0 = constant (use URef everywhere), 1 = logarithmic (requires Z0), 2 = power law (requires PLExp_Hawc).",
    range: "0=constant, 1=log, 2=power law",
    default: "1",
  },
  Z0: {
    param: "Z0",
    desc:  "Surface roughness length for the logarithmic HAWC2 mean wind profile. Typical offshore: 0.03 m; typical onshore: 0.05–0.5 m.",
    unit:  "m",
    default: "0.03",
  },
  UserFile: {
    param: "UserFile",
    desc:  "Path to the user-defined wind DLL for WindType=6. The DLL must implement the InflowWind user-defined wind interface. All DLL-specific parameters must be configured directly in the .dat file.",
  },
};

// ── Wind types ────────────────────────────────────────────────────────────────
const WIND_TYPES = [
  { value: 1, label: "Steady",         desc: "Constant mean speed + power law shear" },
  { value: 3, label: "TurbSim BTS",    desc: "Binary full-field wind file from TurbSim (.bts)" },
  { value: 2, label: "Uniform",        desc: "Time-varying uniform wind from .wnd file" },
  { value: 4, label: "Bladed FF",      desc: "Binary Bladed-style full-field wind (.wnd + .sum)" },
  { value: 5, label: "HAWC2",          desc: "HAWC-format binary wind files (u/v/w components)" },
  { value: 6, label: "User DLL",       desc: "User-defined wind from external DLL (WindType=6)" },
  { value: 7, label: "Native Bladed",  desc: "Native Bladed FF with wind scaling values file" },
];

// ── Auto-name helper ──────────────────────────────────────────────────────────
function autoFilename(windType, p) {
  if (windType === 1) {
    const v = String(Number(p.HWindSpeed).toFixed(1)).replace(".", "p");
    return `IFW_Steady_V${v}.dat`;
  }
  if (windType === 2 && p.Filename_Uni.trim() && p.Filename_Uni !== "none") {
    const base = p.Filename_Uni.trim().split(/[\\/]/).pop().replace(/\.wnd$/i, "");
    return `IFW_Uni_${base}.dat`;
  }
  if (windType === 3 && p.FileName_BTS.trim()) {
    const base = p.FileName_BTS.trim().split(/[\\/]/).pop().replace(/\.bts$/i, "");
    return `IFW_${base}.dat`;
  }
  if ((windType === 4 || windType === 7) && p.FilenameRoot.trim() && p.FilenameRoot !== "none") {
    const base = p.FilenameRoot.trim().split(/[\\/]/).pop().replace(/\.(wnd|sum)$/i, "");
    return windType === 7 ? `IFW_NBladed_${base}.dat` : `IFW_Bladed_${base}.dat`;
  }
  if (windType === 4) return "IFW_Bladed.dat";
  if (windType === 5) return "IFW_HAWC2.dat";
  if (windType === 6) return "IFW_UserDLL.dat";
  if (windType === 7) return "IFW_NativeBladed.dat";
  return "InflowWind.dat";
}

// ── Default parameters ────────────────────────────────────────────────────────
const DEFAULT = {
  WindType:       3,
  PropagationDir: 0.0,
  VFlowAng:       0.0,
  VelInterpCubic: false,
  NWindVel:       1,
  WindVxiList:    0.0,
  WindVyiList:    0.0,
  WindVziList:    90.0,
  // Steady (type 1)
  HWindSpeed:     12.0,
  RefHt:          90.0,
  PLexp:          0.2,
  // Uniform (type 2)
  Filename_Uni:   "none",
  RefHt_Uni:      90.0,
  RefLength:      126.0,
  // TurbSim BTS (type 3)
  FileName_BTS:   "",
  // Bladed FF (type 4 / Native Bladed type 7)
  FilenameRoot:   "none",
  TowerFile:      false,
  // User DLL (type 6)
  UserFile:       "none",
  // HAWC2 (type 5) — file paths
  FileName_u:     "none",
  FileName_v:     "none",
  FileName_w:     "none",
  // HAWC2 grid
  nx: 64, ny: 32, nz: 32,
  dx: 25.0, dy: 2.0, dz: 2.0,
  RefHt_Hawc:     90.0,
  // HAWC2 turbulence scaling
  ScaleMethod:    1,
  SFx: 1.0, SFy: 1.0, SFz: 1.0,
  SigmaFx: 1.2, SigmaFy: 0.8, SigmaFz: 0.2,
  // HAWC2 mean wind profile
  URef:           12.0,
  WindProfile:    1,
  PLExp_Hawc:     0.2,
  Z0:             0.03,
  XOffset:        0,
  // Output
  SumPrint:       false,
};

// ── Parser ────────────────────────────────────────────────────────────────────
function parseInflowWindFile(content) {
  const kv = {};
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    // Skip pure comment / separator / section-header lines
    if (line.startsWith("!") || line.startsWith("=") || /^-{3,}/.test(line)) continue;

    let rest = line;
    let value;

    // Quoted string value
    if (rest.startsWith('"')) {
      const end = rest.indexOf('"', 1);
      if (end === -1) continue;
      value = rest.slice(0, end + 1);
      rest  = rest.slice(end + 1).trim();
    } else {
      // Unquoted: grab up to first whitespace or comma
      const sp = rest.search(/[\s,]/);
      if (sp === -1) continue;
      value = rest.slice(0, sp);
      rest  = rest.slice(sp).trim();
    }

    // Key = next alpha token
    const m = rest.match(/^([A-Za-z_][A-Za-z0-9_]*)/);
    if (!m) continue;
    kv[m[1]] = value;
  }
  return kv;
}

function parsedToState(kv) {
  const bool = (k, d) => (k in kv ? kv[k].toLowerCase() === "true" : d);
  const num  = (k, d) => { if (!(k in kv)) return d; const v = parseFloat(kv[k]); return isNaN(v) ? d : v; };
  const str  = (k, d) => (k in kv ? kv[k].replace(/^"|"$/g, "") : d);

  return {
    ...DEFAULT,
    WindType:       num("WindType",       DEFAULT.WindType),
    PropagationDir: num("PropagationDir", DEFAULT.PropagationDir),
    VFlowAng:       num("VFlowAng",       DEFAULT.VFlowAng),
    VelInterpCubic: bool("VelInterpCubic",DEFAULT.VelInterpCubic),
    NWindVel:       num("NWindVel",       DEFAULT.NWindVel),
    WindVxiList:    num("WindVxiList",    DEFAULT.WindVxiList),
    WindVyiList:    num("WindVyiList",    DEFAULT.WindVyiList),
    WindVziList:    num("WindVziList",    DEFAULT.WindVziList),
    // Steady
    HWindSpeed:     num("HWindSpeed",     DEFAULT.HWindSpeed),
    RefHt:          num("RefHt",          DEFAULT.RefHt),
    PLexp:          num("PLexp",          DEFAULT.PLexp),
    // Uniform
    Filename_Uni:   str("Filename_Uni",   DEFAULT.Filename_Uni),
    RefHt_Uni:      num("RefHt_Uni",      DEFAULT.RefHt_Uni),
    RefLength:      num("RefLength",      DEFAULT.RefLength),
    // BTS
    FileName_BTS:   str("FileName_BTS",   DEFAULT.FileName_BTS),
    // Bladed
    FilenameRoot:   str("FilenameRoot",   DEFAULT.FilenameRoot),
    TowerFile:      bool("TowerFile",     DEFAULT.TowerFile),
    // HAWC2 files
    FileName_u:     str("FileName_u",     DEFAULT.FileName_u),
    FileName_v:     str("FileName_v",     DEFAULT.FileName_v),
    FileName_w:     str("FileName_w",     DEFAULT.FileName_w),
    // HAWC2 grid
    nx:          num("nx",          DEFAULT.nx),
    ny:          num("ny",          DEFAULT.ny),
    nz:          num("nz",          DEFAULT.nz),
    dx:          num("dx",          DEFAULT.dx),
    dy:          num("dy",          DEFAULT.dy),
    dz:          num("dz",          DEFAULT.dz),
    RefHt_Hawc:  num("RefHt_Hawc",  DEFAULT.RefHt_Hawc),
    // HAWC2 turbulence scaling
    ScaleMethod: num("ScaleMethod", DEFAULT.ScaleMethod),
    SFx:         num("SFx",         DEFAULT.SFx),
    SFy:         num("SFy",         DEFAULT.SFy),
    SFz:         num("SFz",         DEFAULT.SFz),
    SigmaFx:     num("SigmaFx",     DEFAULT.SigmaFx),
    SigmaFy:     num("SigmaFy",     DEFAULT.SigmaFy),
    SigmaFz:     num("SigmaFz",     DEFAULT.SigmaFz),
    // HAWC2 mean wind
    URef:        num("URef",        DEFAULT.URef),
    WindProfile: num("WindProfile", DEFAULT.WindProfile),
    PLExp_Hawc:  num("PLExp_Hawc",  DEFAULT.PLExp_Hawc),
    Z0:          num("Z0",          DEFAULT.Z0),
    XOffset:     num("XOffset",     DEFAULT.XOffset),
    // Output
    SumPrint:       bool("SumPrint",      DEFAULT.SumPrint),
    __rawKV__: kv,
  };
}

// ── Builder ───────────────────────────────────────────────────────────────────
function buildInflowWindContent(p) {
  const b   = v  => (v ? "True" : "False");
  const r   = v  => { const n = Number(v); return isNaN(n) ? String(v) : String(n); };
  const pad = sv => String(sv).padEnd(14);
  const q   = v  => `"${v}"`;

  const WRITTEN = new Set([
    "WindType","PropagationDir","VFlowAng","VelInterpCubic",
    "NWindVel","WindVxiList","WindVyiList","WindVziList",
    "HWindSpeed","RefHt","PLexp",
    "Filename_Uni","RefHt_Uni","RefLength",
    "FileName_BTS",
    "FilenameRoot","TowerFile",
    "UserFile",
    "FileName_u","FileName_v","FileName_w",
    "nx","ny","nz","dx","dy","dz","RefHt_Hawc",
    "ScaleMethod","SFx","SFy","SFz","SigmaFx","SigmaFy","SigmaFz",
    "URef","WindProfile","PLExp_Hawc","Z0","XOffset",
    "SumPrint","Echo",
  ]);
  const rawKV = p.__rawKV__ || {};
  const passThrough = Object.entries(rawKV)
    .filter(([k]) => !WRITTEN.has(k) && !k.startsWith("__"))
    .map(([k, v]) => `${String(v).padEnd(14)} ${k}`);

  const lines = [
    `------- InflowWind v3.01.* INPUT FILE ----------------------------------------`,
    `InflowWind input file generated by FlowUrja Studio`,
    `------- SIMULATION CONTROL ---------------------------------------------------`,
    `${pad(b(false))} Echo            - Echo input data to <RootName>.IfW.echo (flag)`,
    `${pad(r(p.WindType))} WindType        - Wind model {1=Steady;2=Uniform;3=TurbSim BTS;4=Bladed;5=HAWC2;6=User DLL;7=User File} (-)`,
    `${pad(r(p.PropagationDir))} PropagationDir  - Wind propagation direction — meteorological convention (degrees)`,
    `${pad(r(p.VFlowAng))} VFlowAng        - Upflow angle (degrees, about y-axis)`,
    `${pad(b(p.VelInterpCubic))} VelInterpCubic  - Cubic temporal interpolation (flag)`,
    `${pad(r(p.NWindVel))} NWindVel        - Number of wind velocity output points [0–9] (-)`,
    `${pad(r(p.WindVxiList))} WindVxiList     - X-coordinates for wind velocity output (m)`,
    `${pad(r(p.WindVyiList))} WindVyiList     - Y-coordinates for wind velocity output (m)`,
    `${pad(r(p.WindVziList))} WindVziList     - Z-coordinates for wind velocity output (m)`,
    `================== Parameters for Steady Wind [WindType=1] ====================`,
    `${pad(r(p.HWindSpeed))} HWindSpeed      - Horizontal wind speed (m/s)`,
    `${pad(r(p.RefHt))} RefHt           - Reference height for wind speed (m)`,
    `${pad(r(p.PLexp))} PLexp           - Power law exponent (-)`,
    `================== Parameters for Uniform Wind [WindType=2] ===================`,
    `${pad(q(p.Filename_Uni))} Filename_Uni    - Uniform wind file (.wnd)`,
    `${pad(r(p.RefHt_Uni))} RefHt_Uni       - Reference height for uniform wind (m)`,
    `${pad(r(p.RefLength))} RefLength       - Reference length for shear (m)`,
    `================== Parameters for Binary TurbSim FF [WindType=3] ==============`,
    `${pad(q(p.FileName_BTS))} FileName_BTS    - TurbSim binary wind field file (.bts)`,
    `================== Parameters for User-Defined wind [WindType=6] ==============`,
    `${pad(q(p.UserFile))} UserFile        - Path to user-defined DLL wind file`,
    `================== Parameters for Binary Bladed-style FF [WindType=4] =========`,
    `${pad(q(p.FilenameRoot))} FilenameRoot    - Root name of Bladed FF wind file`,
    `${pad(b(p.TowerFile))} TowerFile       - Have tower file (.twr) (flag)`,
    `================== Parameters for HAWC-format binary files [WindType=5] =======`,
    `${pad(q(p.FileName_u))} FileName_u      - u-component wind file (.bin)`,
    `${pad(q(p.FileName_v))} FileName_v      - v-component wind file (.bin)`,
    `${pad(q(p.FileName_w))} FileName_w      - w-component wind file (.bin)`,
    `${pad(r(p.nx))} nx              - grids in x (-)`,
    `${pad(r(p.ny))} ny              - grids in y (-)`,
    `${pad(r(p.nz))} nz              - grids in z (-)`,
    `${pad(r(p.dx))} dx              - x grid spacing (m)`,
    `${pad(r(p.dy))} dy              - y grid spacing (m)`,
    `${pad(r(p.dz))} dz              - z grid spacing (m)`,
    `${pad(r(p.RefHt_Hawc))} RefHt_Hawc      - HAWC reference height (m)`,
    `${pad(r(p.ScaleMethod))} ScaleMethod     - Turbulence scaling method (-)`,
    `${pad(r(p.SFx))} SFx             - x scaling factor (-)`,
    `${pad(r(p.SFy))} SFy             - y scaling factor (-)`,
    `${pad(r(p.SFz))} SFz             - z scaling factor (-)`,
    `${pad(r(p.SigmaFx))} SigmaFx         - x turbulence std dev target (m/s)`,
    `${pad(r(p.SigmaFy))} SigmaFy         - y turbulence std dev target (m/s)`,
    `${pad(r(p.SigmaFz))} SigmaFz         - z turbulence std dev target (m/s)`,
    `${pad(r(p.URef))} URef            - Mean u-component at reference height (m/s)`,
    `${pad(r(p.WindProfile))} WindProfile     - Wind profile type (0=const; 1=log; 2=power law) (-)`,
    `${pad(r(p.PLExp_Hawc))} PLExp_Hawc      - Power law exponent for HAWC (-)`,
    `${pad(r(p.Z0))} Z0              - Surface roughness length (m)`,
    `${pad(r(p.XOffset))} XOffset         - Initial x offset (m)`,
    `================== LIDAR Parameters ==========================================`,
    `${pad("0")} SensorType          - Lidar sensor type (0=None) (-)`,
    `${pad("0")} NumPulseGate        - Number of lidar measurement gates (-)`,
    `${pad("30")} PulseSpacing        - Distance between range gates (m)`,
    `${pad("0")} NumBeam             - Number of lidar beams (0-5)`,
    `${pad("-200")} FocalDistanceX      - Focal distance X (m)`,
    `${pad("0")} FocalDistanceY      - Focal distance Y (m)`,
    `${pad("0")} FocalDistanceZ      - Focal distance Z (m)`,
    `${pad("0.0 0.0 0.0")} RotorApexOffsetPos  - Offset of lidar from hub height (m)`,
    `${pad("0")} URefLid             - Reference wind speed for lidar (m/s)`,
    `${pad("0.25")} MeasurementInterval - Time between measurements (s)`,
    `${pad(b(false))} LidRadialVel        - Return radial component (flag)`,
    `${pad("1")} ConsiderHubMotion   - Consider hub motion impact on lidar (flag)`,
    `================== OUTPUT ====================================================`,
    `${pad(b(p.SumPrint))} SumPrint        - Print summary to <RootName>.IfW.sum (flag)`,
    `              OutList         - Output channels`,
    `"Wind1VelX"`,
    `"Wind1VelY"`,
    `"Wind1VelZ"`,
    `END of input file (the word "END" must appear in the first 3 columns of this last OutList line)`,
    `---------------------------------------------------------------------------------------`,
  ];

  if (passThrough.length) {
    lines.push(
      "!--- Parameters not editable in this UI (preserved verbatim from original file) ---",
      ...passThrough,
    );
  }

  return lines.join("\n");
}

// ── Patch writer ──────────────────────────────────────────────────────────────
// Used when SAVING an existing file.
// Walks the original content line-by-line; for every line whose key is in our
// VALUE_MAP it replaces only the value token, leaving everything else byte-for-byte
// identical (LIDAR params, HAWC2 section, comments, whitespace, section order).
// Each key is patched at most once (first occurrence) — safe when the same
// parameter name reappears in a different section (e.g. RefHt in HAWC2).
function patchInflowWindContent(originalContent, p) {
  const b = v => (v ? "True" : "False");
  const r = v => { const n = Number(v); return isNaN(n) ? String(v) : String(n); };
  const q = v => `"${v}"`;

  // Map of key → new formatted value (all keys exposed in the UI)
  const VALUE_MAP = {
    WindType:       r(p.WindType),
    PropagationDir: r(p.PropagationDir),
    VFlowAng:       r(p.VFlowAng),
    VelInterpCubic: b(p.VelInterpCubic),
    NWindVel:       r(p.NWindVel),
    WindVxiList:    r(p.WindVxiList),
    WindVyiList:    r(p.WindVyiList),
    WindVziList:    r(p.WindVziList),
    // Steady
    HWindSpeed:     r(p.HWindSpeed),
    RefHt:          r(p.RefHt),
    PLexp:          r(p.PLexp),
    // Uniform
    Filename_Uni:   q(p.Filename_Uni),
    RefHt_Uni:      r(p.RefHt_Uni),
    RefLength:      r(p.RefLength),
    // BTS
    FileName_BTS:   q(p.FileName_BTS),
    // Bladed
    FilenameRoot:   q(p.FilenameRoot),
    TowerFile:      b(p.TowerFile),
    // User DLL
    UserFile:       q(p.UserFile),
    // HAWC2 files
    FileName_u:     q(p.FileName_u),
    FileName_v:     q(p.FileName_v),
    FileName_w:     q(p.FileName_w),
    // HAWC2 grid
    nx:          r(p.nx),
    ny:          r(p.ny),
    nz:          r(p.nz),
    dx:          r(p.dx),
    dy:          r(p.dy),
    dz:          r(p.dz),
    RefHt_Hawc:  r(p.RefHt_Hawc),
    // HAWC2 turbulence scaling
    ScaleMethod: r(p.ScaleMethod),
    SFx:         r(p.SFx),
    SFy:         r(p.SFy),
    SFz:         r(p.SFz),
    SigmaFx:     r(p.SigmaFx),
    SigmaFy:     r(p.SigmaFy),
    SigmaFz:     r(p.SigmaFz),
    // HAWC2 mean wind
    URef:        r(p.URef),
    WindProfile: r(p.WindProfile),
    PLExp_Hawc:  r(p.PLExp_Hawc),
    Z0:          r(p.Z0),
    XOffset:     r(p.XOffset),
    // Output
    SumPrint:       b(p.SumPrint),
  };

  const alreadyPatched = new Set(); // patch each key at most once

  return originalContent.split("\n").map(rawLine => {
    const trimmed = rawLine.trim();
    // Skip blanks, comments, separator lines, section headers
    if (!trimmed
      || trimmed.startsWith("!")
      || trimmed.startsWith("=")
      || /^-{3,}/.test(trimmed)) return rawLine;

    // ── Extract the value token and what follows it ───────────────────────
    let origValueToken, afterValue;
    if (trimmed.startsWith('"')) {
      const end = trimmed.indexOf('"', 1);
      if (end === -1) return rawLine;
      origValueToken = trimmed.slice(0, end + 1);
      afterValue     = trimmed.slice(end + 1);
    } else {
      const sp = trimmed.search(/\s/);
      if (sp === -1) return rawLine;
      origValueToken = trimmed.slice(0, sp);
      afterValue     = trimmed.slice(sp);
    }

    // ── Extract the key (first alpha token after the value) ───────────────
    const keyMatch = afterValue.trimStart().match(/^([A-Za-z_][A-Za-z0-9_]*)/);
    if (!keyMatch) return rawLine;
    const key = keyMatch[1];

    if (!(key in VALUE_MAP))     return rawLine; // not one of our keys
    if (alreadyPatched.has(key)) return rawLine; // already updated once
    alreadyPatched.add(key);

    // ── Replace value, preserve leading whitespace + everything after ─────
    const newValue   = VALUE_MAP[key];
    const leadingWS  = rawLine.slice(0, rawLine.length - rawLine.trimStart().length);
    // Keep column alignment: pad at least as wide as the original token
    const padWidth   = Math.max(origValueToken.length, String(newValue).length, 14);
    const paddedNew  = String(newValue).padEnd(padWidth);

    return `${leadingWS}${paddedNew}${afterValue}`;
  }).join("\n");
}

// ── Field label with info popover ────────────────────────────────────────────
// Defined at module level — NOT inside the component — so React can correctly
// identify it as the same component type across parent re-renders. Defining it
// inside the component would create a new function reference every render,
// causing React to unmount+remount the InfoPopover subtree and reset its open
// state, making the ⓘ button appear broken.
function Lbl({ children, k }) {
  return (
    <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
      {children}
      <InfoPopover content={INFO[k]} accentColor={ACCENT} />
    </span>
  );
}

// ── Wind visualisation SVG ─────────────────────────────────────────────────────
// Shows a turbine (right) + horizontal shear arrows (left) — longer at top.
// For Steady: lengths follow a rough power-law gradient.
// For BTS: same arrows but slightly irregular to hint at turbulence.
function WindVizSVG({ windType, windSpeed, plExp }) {
  const c = "#378ADD";

  // [svgY, relativeLen] pairs — top to bottom = high altitude to low altitude
  const arrowRows = [
    [16, 1.00],
    [29, 0.83],
    [42, 0.67],
    [55, 0.52],
    [68, 0.39],
  ];
  const MAX_LEN = 24;

  return (
    <svg viewBox="0 0 100 110" width="100%" height="180" style={{ display: "block" }}>
      {/* Tower */}
      <line x1="68" y1="54" x2="68" y2="100"
        style={{ stroke: "var(--tx-4)" }} strokeWidth="5" strokeLinecap="round"/>
      {/* Base */}
      <line x1="56" y1="101" x2="80" y2="101"
        style={{ stroke: "var(--bd-strong)" }} strokeWidth="2"/>
      {/* Nacelle */}
      <rect x="60" y="48" width="16" height="8" rx="2"
        style={{ fill: "var(--bg-hover-md)" }}/>
      {/* Hub */}
      <circle cx="68" cy="52" r="3.5" fill={c}/>
      {/* Blades — up, lower-left, lower-right */}
      <line x1="68" y1="48" x2="68" y2="14"  stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      <line x1="65" y1="55" x2="42" y2="68"  stroke={c} strokeWidth="2.5" strokeLinecap="round"/>
      <line x1="71" y1="55" x2="94" y2="68"  stroke={c} strokeWidth="2.5" strokeLinecap="round"/>

      {/* Shear arrows */}
      {arrowRows.map(([y, rel], i) => {
        const len = MAX_LEN * rel;
        // For BTS: slight vertical wobble to hint at turbulence
        const dy  = windType === 3 ? ((i * 7) % 5) - 2 : 0;
        return (
          <g key={y} opacity="0.62">
            <line x1="4" y1={y + dy} x2={4 + len} y2={y + dy}
              stroke={c} strokeWidth="1.4" strokeLinecap="round"/>
            <polyline
              points={`${4 + len - 5},${y + dy - 3.5} ${4 + len},${y + dy} ${4 + len - 5},${y + dy + 3.5}`}
              stroke={c} strokeWidth="1.4" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
          </g>
        );
      })}

      {/* Module label */}
      <text x="4" y="108" fontSize="6"
        style={{ fill: c }} fontFamily="-apple-system,sans-serif" opacity="0.7">
        {windType === 1
          ? `Steady  ${Number(windSpeed || 0).toFixed(1)} m/s  α=${plExp}`
          : windType === 2
          ? "Uniform (.wnd)"
          : windType === 3
          ? "TurbSim BTS"
          : "InflowWind"}
      </text>
    </svg>
  );
}

// ── Toggle ────────────────────────────────────────────────────────────────────
function Toggle({ value, onChange, label, disabled }) {
  return (
    <div className={s.toggleRow}>
      <button
        type="button"
        disabled={disabled}
        className={`${s.toggle} ${value ? s.on : ""}`}
        onClick={() => !disabled && onChange(!value)}
      >
        <span className={s.toggleThumb} />
      </button>
      {label && <span className={s.toggleLabel}>{label}</span>}
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────
export default function InflowWindPanel({
  onLog, project,
  filePathFromProject, reloadKey, onDirtyChange, onRegisterSave,
  onWindParamsChange,
  simRunning = false,
}) {
  const [p,             _setP]          = useState(DEFAULT);
  const [filePath,      setFilePath]    = useState("");
  const [isDirtyFlag,   setIsDirtyFlag] = useState(false);
  const [btsFiles,      setBtsFiles]    = useState([]);
  const [scanning,      setScanning]    = useState(false);
  const [showRaw,       setShowRaw]     = useState(false);
  const [rawContent,    setRawContent]  = useState("");
  const [generating,    setGenerating]  = useState(false);
  const [customDatName, setCustomDatName] = useState("");

  // Ref holds JSON snapshot of last saved/loaded state — written synchronously
  // to avoid React batching race between setP and the snapshot update.
  const originalRef = useRef(null);

  // Ref holds the raw file text of the currently loaded file.
  // handleSave uses patchInflowWindContent() on this to update only the known
  // keys while leaving every other line (LIDAR, HAWC2, Bladed…) untouched.
  // handleGenerate stores the freshly created template here so subsequent saves
  // also use the patch strategy from that point on.
  const originalContentRef = useRef("");

  // Wrapped setP — marks panel dirty on every user-driven change
  const setP = useCallback((updater) => {
    _setP(updater);
    setIsDirtyFlag(true);
  }, []);

  // isDirty: file open + user touched something + state diverged from snapshot
  const isDirty = !!filePath && isDirtyFlag &&
    originalRef.current !== null && JSON.stringify(p) !== originalRef.current;

  // Revert detection: clear dirty flag if user undid all their changes
  useEffect(() => {
    if (!isDirtyFlag || originalRef.current === null) return;
    if (JSON.stringify(p) === originalRef.current) setIsDirtyFlag(false);
  }, [p, isDirtyFlag]); // eslint-disable-line react-hooks/exhaustive-deps

  const set    = key => e => setP(prev => ({ ...prev, [key]: e.target.value }));
  // Numbers must be stored as Number (not string) so JSON.stringify comparison
  // works correctly for the revert-detection / isDirty logic.
  const setNum = key => e => setP(prev => ({ ...prev, [key]: Number(e.target.value) }));

  const autoName         = useMemo(() => autoFilename(p.WindType, p), [p.WindType, p.HWindSpeed, p.FileName_BTS, p.Filename_Uni, p.FilenameRoot]); // eslint-disable-line react-hooks/exhaustive-deps
  const effectiveDatName = customDatName.trim() || autoName;

  // ── File operations ────────────────────────────────────────────────────────

  const loadFile = async (path) => {
    try {
      const content  = await invoke("read_text_file", { path });
      const kv       = parseInflowWindFile(content);
      const newState = parsedToState(kv);
      originalContentRef.current = content;          // raw text for patch writes
      originalRef.current = JSON.stringify(newState); // JSON snapshot for dirty detection
      _setP(newState);
      setIsDirtyFlag(false);
      onLog?.("ok", `Loaded ${path.split("/").pop()}`);
    } catch {
      // File is missing — auto-generate it from defaults so that subsequent
      // patchInputFileKey calls from the OpenFAST run card have a valid file
      // to read-and-patch (on Windows the file often doesn't exist until it is
      // explicitly saved, which caused the one-way sync problem).
      const fallback = { ...DEFAULT };
      const content  = buildInflowWindContent(fallback);
      try {
        await invoke("write_text_file", { path, content });
        originalContentRef.current = content;
        originalRef.current = JSON.stringify(fallback);
        _setP(fallback);
        onLog?.("info", `${path.split("/").pop()} not found — created with defaults`);
      } catch {
        // Model directory may not exist yet (project not fully configured) — stay silent
      }
    }
  };

  const handleOpen = async () => {
    try {
      const f = await openDialog({
        multiple: false, directory: false,
        filters: [{ name: "InflowWind input", extensions: ["dat"] }],
      });
      if (!f) return;
      setFilePath(f);
      await loadFile(f);
    } catch {}
  };

  const handleSave = useCallback(async () => {
    if (simRunning) {
      onLog?.("warn", "⚠ OpenFAST is running — save blocked to protect the active simulation. Wait for it to finish.");
      return;
    }
    if (!filePath) {
      onLog?.("warn", "No file open — use Open .dat or Generate first.");
      return;
    }
    // Patch strategy: only the UI-known values change; every other line
    // (LIDAR section, HAWC2 section, Bladed section, custom comments…)
    // is left exactly as it was in the file we originally read.
    const content = originalContentRef.current
      ? patchInflowWindContent(originalContentRef.current, p)
      : buildInflowWindContent(p); // fallback for programmatically set paths
    try {
      await invoke("write_text_file", { path: filePath, content });
      originalContentRef.current = content;          // patch from the saved version next time
      originalRef.current = JSON.stringify(p);       // advance dirty snapshot
      setIsDirtyFlag(false);
      onLog?.("ok", `Saved ${filePath.split("/").pop()}`);
    } catch (err) {
      onLog?.("error", `Save failed: ${String(err)}`);
    }
  }, [filePath, p]); // eslint-disable-line react-hooks/exhaustive-deps

  // Generate a new file in the project dir, then treat it as the loaded file
  const handleGenerate = async () => {
    if (!project) { onLog?.("warn", "Open a project directory first."); return; }
    if (p.WindType === 3 && !p.FileName_BTS.trim()) { onLog?.("warn", "Select a .bts file first."); return; }
    setGenerating(true);
    const outPath = `${project.modelDir ?? project.workingDir}/${effectiveDatName}`;
    const content = buildInflowWindContent(p);
    try {
      await invoke("write_text_file", { path: outPath, content });
      // Treat the generated file as the "open" file — store raw content so
      // subsequent saves use the patch strategy (preserving any future manual edits
      // to the file outside this app).
      originalContentRef.current = content;
      originalRef.current = JSON.stringify(p);
      setFilePath(outPath);
      setIsDirtyFlag(false);
      onLog?.("ok", `Generated → ${outPath}`);
    } catch (err) {
      onLog?.("error", `Write failed: ${err.message ?? err}`);
    }
    setGenerating(false);
  };

  const handleViewRaw = async () => {
    if (!filePath) {
      onLog?.("warn", "Load or save the InflowWind file first — then View will show the actual file on disk.");
      return;
    }
    try {
      const content = await invoke("read_text_file", { path: filePath });
      setRawContent(content);
      setShowRaw(true);
    } catch (err) {
      onLog?.("error", `Cannot read file: ${err}`);
    }
  };

  // Cmd+S / Ctrl+S to save
  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "s") { e.preventDefault(); handleSave(); }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [handleSave]);

  // ── Project integration effects ────────────────────────────────────────────
  useEffect(() => {
    if (!filePathFromProject) return;
    setFilePath(filePathFromProject);
    loadFile(filePathFromProject);
  }, [filePathFromProject]); // eslint-disable-line react-hooks/exhaustive-deps

  // Reload from disk when OpenFASTPanel patches the inflowwind file externally
  useEffect(() => {
    if (!reloadKey || !filePathFromProject) return;
    loadFile(filePathFromProject);
  }, [reloadKey]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { onDirtyChange?.(isDirty); }, [isDirty]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { onRegisterSave?.(handleSave); }, [handleSave]); // eslint-disable-line react-hooks/exhaustive-deps

  // Broadcast live wind params to the OpenFAST run panel whenever the user
  // changes WindType, wind speed, or BTS file — no save required.
  useEffect(() => {
    if (!filePath || !onWindParamsChange) return;
    const btsBasename = p.FileName_BTS
      ? p.FileName_BTS.replace(/\\/g, "/").split("/").pop()
      : "";
    onWindParamsChange(p.WindType, String(p.HWindSpeed), btsBasename);
  }, [p.WindType, p.HWindSpeed, p.FileName_BTS]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── BTS scanning ───────────────────────────────────────────────────────────
  const scanBts = useCallback(async () => {
    if (!project) return;
    setScanning(true);
    try {
      const raw = await invoke("sidecar_call", {
        payload: JSON.stringify({ cmd: "list_bts_files", working_dir: project.windDir ?? project.workingDir }),
      });
      const res = JSON.parse(raw);
      if (res.ok) setBtsFiles(res.files);
    } catch {}
    setScanning(false);
  }, [project]);

  useEffect(() => { if (project) scanBts(); }, [project, scanBts]);

  const browseBts = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "TurbSim wind field", extensions: ["bts"] }] });
      if (f) setP(prev => ({ ...prev, FileName_BTS: f }));
    } catch {}
  };

  const browseWnd = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "Uniform wind file", extensions: ["wnd"] }] });
      if (f) setP(prev => ({ ...prev, Filename_Uni: f }));
    } catch {}
  };

  const browseBladed = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "Bladed wind file", extensions: ["wnd", "sum"] }] });
      if (f) setP(prev => ({ ...prev, FilenameRoot: f.replace(/\.(wnd|sum)$/i, "") }));
    } catch {}
  };

  const browseHawc = async (key, exts) => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "HAWC2 wind component", extensions: exts }] });
      if (f) setP(prev => ({ ...prev, [key]: f }));
    } catch {}
  };

  const browseUserFile = async () => {
    try {
      const f = await openDialog({ multiple: false, filters: [{ name: "User DLL", extensions: ["dll", "so", "dylib"] }] });
      if (f) setP(prev => ({ ...prev, UserFile: f }));
    } catch {}
  };

  // ── Derived display values ─────────────────────────────────────────────────
  const wt = WIND_TYPES.find(t => t.value === p.WindType);

  const displayPath = filePath
    ? filePath.replace(/\\/g, "/").split("/").slice(-3).join("/")
    : "";

  // Sidebar stats — always show Type + Hub Ht; add wind-type-specific cards
  const stats = [
    { k: "Type",       v: wt?.label || "—" },
    { k: "Hub height", v: `${p.WindVziList} m` },
    ...(p.WindType === 1 ? [
      { k: "Wind speed", v: `${Number(p.HWindSpeed).toFixed(1)} m/s` },
      { k: "Ref height", v: `${p.RefHt} m` },
      { k: "Shear α",    v: String(p.PLexp) },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
    ] : p.WindType === 2 ? [
      { k: "Ref height", v: `${p.RefHt_Uni} m` },
      { k: "Ref length", v: `${p.RefLength} m` },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
    ] : p.WindType === 6 ? [
      { k: "DLL file",   v: p.UserFile !== "none" ? p.UserFile.split(/[\\/]/).pop() : "—" },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
    ] : p.WindType === 4 || p.WindType === 7 ? [
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
      { k: "Tower file", v: p.TowerFile ? "Yes" : "No" },
    ] : p.WindType === 5 ? [
      { k: "Grid",       v: `${p.nx}×${p.ny}×${p.nz}` },
      { k: "Spacing",    v: `${p.dx}×${p.dy}×${p.dz} m` },
      { k: "U ref",      v: `${p.URef} m/s` },
      { k: "Profile",    v: p.WindProfile === 0 ? "Constant" : p.WindProfile === 1 ? "Log" : "Power law" },
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
    ] : [
      { k: "Prop. dir",  v: `${p.PropagationDir}°` },
      { k: "Upflow",     v: `${p.VFlowAng}°` },
    ]),
  ];

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className={s.panel}>

      {/* ── Header ────────────────────────────────────────────────────────── */}
      <div className={s.header}>
        <Cloud size={14} strokeWidth={1.8} className={s.headerIcon} />
        <span className={s.title}>InflowWind</span>
        <span className={s.subtitle}>inflow conditions</span>
        <span className={s.badge}>v3.01</span>
        <div style={{ flex: 1 }} />
        <button className={`${s.headerBtn} ${s.headerBtnPrimary}`} onClick={handleOpen} type="button">
          <FolderOpen size={12} strokeWidth={1.8} /> Open .dat
        </button>
        <button className={s.eyeBtn} onClick={handleViewRaw} title="Preview .dat content" type="button">
          <Eye size={12} strokeWidth={1.8} />
          View .dat
        </button>
      </div>

      {/* ── File bar — always visible, Save lives here ────────────────────── */}
      <div className={[s.fileBar, filePath ? s.fileBarLoaded : ""].join(" ")}>
        <span className={`${s.filePath} ${filePath ? s.filePathSet : ""}`}>
          {filePath
            ? (displayPath || filePath.split("/").pop())
            : "No file open — click Open .dat to load an existing file"}
        </span>
        <span className={s.dirtyDot} style={{ opacity: isDirty ? 1 : 0 }} title="Unsaved changes" />
        <button
          className={[s.saveBtn, (!isDirty || simRunning) ? s.saveBtnInactive : ""].join(" ")}
          onClick={(!isDirty || simRunning) ? undefined : handleSave}
          type="button"
          title={simRunning ? "OpenFAST is running — save blocked" : "Save (⌘S)"}
        >
          <Save size={11} strokeWidth={2} /> Save
        </button>
      </div>

      {/* ── Simulation running banner ──────────────────────────────────────── */}
      {simRunning && (
        <div style={{
          display: "flex", alignItems: "center", gap: 8,
          padding: "7px 18px",
          background: "rgba(217,119,6,0.10)",
          borderBottom: "0.5px solid rgba(217,119,6,0.28)",
          flexShrink: 0,
        }}>
          <span style={{ fontSize: 13 }}>⚠</span>
          <span style={{ fontSize: 12, fontWeight: 500, color: "#92400E" }}>
            OpenFAST is running — saving is disabled to protect the active simulation
          </span>
        </div>
      )}

      {/* ── Raw file modal ─────────────────────────────────────────────────── */}
      {showRaw && rawContent && (
        <RawFileModal
          content={rawContent}
          filename={filePath ? filePath.split("/").pop() : "InflowWind.dat"}
          fromDisk={!!filePath}
          hasDirtyWarning={isDirty}
          filePath={filePath}
          onSaved={(newContent) => { setRawContent(newContent); loadFile(filePath); }}
          onClose={() => setShowRaw(false)}
        />
      )}

      {/* ── Content row ───────────────────────────────────────────────────── */}
      <div className={s.contentRow}>

        {/* Form area */}
        <div className={s.scroll}>
          <div className={s.form}>

            {/* Wind Source */}
            <p className={s.sectionHead}>
              Wind Source
              <InfoPopover content={INFO.WindType} accentColor={ACCENT} />
            </p>

            <div className={s.typeBar}>
              {WIND_TYPES.map(t => (
                <button
                  key={t.value}
                  type="button"
                  className={`${s.typeBtn} ${p.WindType === t.value ? s.typeBtnActive : ""}`}
                  onClick={() => setP(prev => ({ ...prev, WindType: t.value }))}
                >
                  {t.label}
                </button>
              ))}
            </div>
            <p className={s.typeDesc}>{wt?.desc}</p>

            {/* VelInterpCubic — shown but disabled for WindType=1 */}
            <div className={s.field}
              style={{ marginTop: 8 }}
              title={p.WindType === 1 ? "Not used for WindType=1 (Steady). Enable with wind types 2–7 for cubic temporal interpolation." : undefined}
            >
              <span className={s.fieldLabel}>
                <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
                  Cubic time interpolation
                  <InfoPopover content={INFO.VelInterpCubic} accentColor={ACCENT} />
                </span>
              </span>
              <Toggle
                value={p.VelInterpCubic}
                onChange={v => setP(prev => ({ ...prev, VelInterpCubic: v }))}
                label="VelInterpCubic"
                disabled={p.WindType === 1}
              />
            </div>

            {/* ── Steady params ──────────────────────────────────────────── */}
            {p.WindType === 1 && (
              <div className={s.sourceCard}>
              <div className={s.grid2}>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="HWindSpeed">Wind speed</Lbl></span>
                  <div className={s.inputRow}>
                    <input className={s.inp} type="number" value={p.HWindSpeed} onChange={setNum("HWindSpeed")} step="0.5" />
                    <span className={s.unit}>m/s</span>
                  </div>
                </label>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="RefHt">Reference height</Lbl></span>
                  <div className={s.inputRow}>
                    <input className={s.inp} type="number" value={p.RefHt} onChange={setNum("RefHt")} />
                    <span className={s.unit}>m</span>
                  </div>
                </label>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="PLexp">Power law exponent α</Lbl></span>
                  <input className={s.inp} type="number" value={p.PLexp} onChange={setNum("PLexp")} step="0.01" />
                </label>
              </div>
              </div>
            )}

            {/* ── Uniform wind params ────────────────────────────────────── */}
            {p.WindType === 2 && (
              <div className={s.sourceCard}>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="Filename_Uni">Wind file (.wnd)</Lbl></span>
                  <div className={s.fileRow}>
                    <input className={s.inp} type="text" value={p.Filename_Uni === "none" ? "" : p.Filename_Uni}
                      onChange={e => setP(prev => ({ ...prev, Filename_Uni: e.target.value || "none" }))}
                      placeholder="Path to .wnd file…" />
                    <button className={s.browseBtn} onClick={browseWnd} title="Browse" type="button">
                      <FolderOpen size={13} strokeWidth={1.8} />
                    </button>
                  </div>
                </label>
                <div className={s.grid2} style={{ marginTop: 12 }}>
                  <label className={s.field}>
                    <span className={s.fieldLabel}><Lbl k="RefHt_Uni">Reference height</Lbl></span>
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.RefHt_Uni} onChange={setNum("RefHt_Uni")} />
                      <span className={s.unit}>m</span>
                    </div>
                  </label>
                  <label className={s.field}>
                    <span className={s.fieldLabel}><Lbl k="RefLength">Reference length</Lbl></span>
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.RefLength} onChange={setNum("RefLength")} />
                      <span className={s.unit}>m</span>
                    </div>
                  </label>
                </div>
              </div>
            )}

            {/* ── TurbSim BTS params ─────────────────────────────────────── */}
            {p.WindType === 3 && (
              <div className={s.sourceCard}>
                <label className={s.field}>
                  <span className={s.fieldLabel}><Lbl k="FileName_BTS">Wind field file (.bts)</Lbl></span>
                  <div className={s.fileRow}>
                    <input className={s.inp} type="text" value={p.FileName_BTS}
                      onChange={set("FileName_BTS")} placeholder="Path to .bts file…" />
                    <button className={s.browseBtn} onClick={browseBts} title="Browse" type="button">
                      <FolderOpen size={13} strokeWidth={1.8} />
                    </button>
                  </div>
                </label>

                {project && (
                  <div className={s.scanRow}>
                    <button className={s.scanBtn} onClick={scanBts} disabled={scanning} type="button">
                      <RefreshCw size={11} strokeWidth={2} className={scanning ? s.spinning : ""} />
                      {scanning ? "Scanning…" : "Scan project"}
                    </button>
                    {btsFiles.length > 0 ? (
                      <div className={s.btsPickerWrap}>
                        <select className={s.btsPicker} value={p.FileName_BTS}
                          onChange={e => e.target.value && setP(prev => ({ ...prev, FileName_BTS: e.target.value }))}>
                          <option value="">— {btsFiles.length} .bts files found —</option>
                          {btsFiles.map(f => (
                            <option key={f.path} value={f.path}>{f.rel}</option>
                          ))}
                        </select>
                        <ChevronDown size={12} className={s.btsChevron} />
                      </div>
                    ) : !scanning && (
                      <span className={s.noBts}>No .bts files — run TurbSim or DLC Batch first</span>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* ── Bladed FF params (type 4 and 7) ───────────────────────── */}
            {(p.WindType === 4 || p.WindType === 7) && (
              <div className={s.sourceCard}>
                <label className={s.field}>
                  <span className={s.fieldLabel}>
                    <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      {p.WindType === 4 ? "Root filename (.wnd/.sum)" : "Scaling values file"}
                      <InfoPopover content={INFO.FilenameRoot} accentColor={ACCENT} />
                    </span>
                  </span>
                  <div className={s.fileRow}>
                    <input className={s.inp} type="text"
                      value={p.FilenameRoot === "none" ? "" : p.FilenameRoot}
                      onChange={e => setP(prev => ({ ...prev, FilenameRoot: e.target.value || "none" }))}
                      placeholder={p.WindType === 4 ? "Root path (no extension)…" : "Path to scaling values file…"} />
                    <button className={s.browseBtn} onClick={browseBladed} title="Browse" type="button">
                      <FolderOpen size={13} strokeWidth={1.8} />
                    </button>
                  </div>
                </label>
                {p.WindType === 4 && (
                  <div className={s.field} style={{ marginTop: 10 }}>
                    <span className={s.fieldLabel}>
                      <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
                        Tower file
                        <InfoPopover content={INFO.TowerFile} accentColor={ACCENT} />
                      </span>
                    </span>
                    <Toggle
                      value={p.TowerFile}
                      onChange={v => setP(prev => ({ ...prev, TowerFile: v }))}
                      label="Include tower wind data (.twr)"
                    />
                  </div>
                )}
              </div>
            )}

            {/* ── HAWC2 params (type 5) ──────────────────────────────────── */}
            {p.WindType === 5 && (
              <div className={s.sourceCard}>
                {/* File pickers */}
                {[
                  { key: "FileName_u", label: "u-component file (.bin)", exts: ["bin"] },
                  { key: "FileName_v", label: "v-component file (.bin)", exts: ["bin"] },
                  { key: "FileName_w", label: "w-component file (.bin)", exts: ["bin"] },
                ].map(({ key, label, exts }) => (
                  <label key={key} className={s.field}>
                    <span className={s.fieldLabel}>{label}</span>
                    <div className={s.fileRow}>
                      <input className={s.inp} type="text"
                        value={p[key] === "none" ? "" : p[key]}
                        onChange={e => setP(prev => ({ ...prev, [key]: e.target.value || "none" }))}
                        placeholder={`Path to ${label}…`} />
                      <button className={s.browseBtn} onClick={() => browseHawc(key, exts)} title="Browse" type="button">
                        <FolderOpen size={13} strokeWidth={1.8} />
                      </button>
                    </div>
                  </label>
                ))}

                {/* Grid dimensions */}
                <p className={s.sectionHead} style={{ marginTop: 14 }}>Wind Box Grid</p>
                <div className={s.grid3}>
                  {[
                    { k: "nx", label: "nx (x points)" },
                    { k: "ny", label: "ny (y points)" },
                    { k: "nz", label: "nz (z points)" },
                  ].map(({ k, label }) => (
                    <label key={k} className={s.field}>
                      <span className={s.fieldLabel}>{label}</span>
                      <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} min="1" step="1" />
                    </label>
                  ))}
                  {[
                    { k: "dx", label: "dx (m)", u: "m" },
                    { k: "dy", label: "dy (m)", u: "m" },
                    { k: "dz", label: "dz (m)", u: "m" },
                  ].map(({ k, label, u }) => (
                    <label key={k} className={s.field}>
                      <span className={s.fieldLabel}>{label}</span>
                      <div className={s.inputRow}>
                        <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} step="0.5" />
                        <span className={s.unit}>{u}</span>
                      </div>
                    </label>
                  ))}
                  <label className={s.field}>
                    <span className={s.fieldLabel}>RefHt_Hawc</span>
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.RefHt_Hawc} onChange={setNum("RefHt_Hawc")} />
                      <span className={s.unit}>m</span>
                    </div>
                  </label>
                </div>

                {/* Turbulence scaling */}
                <p className={s.sectionHead} style={{ marginTop: 14 }}>
                  Turbulence Scaling
                  <InfoPopover content={INFO.ScaleMethod} accentColor={ACCENT} />
                </p>
                <label className={s.field}>
                  <span className={s.fieldLabel}>Scale method</span>
                  <select className={s.inp} value={p.ScaleMethod} onChange={setNum("ScaleMethod")}>
                    <option value={0}>0 — None (raw values)</option>
                    <option value={1}>1 — Direct scale factors (SF)</option>
                    <option value={2}>2 — Target standard deviation (Sigma)</option>
                  </select>
                </label>
                {p.ScaleMethod === 1 && (
                  <div className={s.grid3} style={{ marginTop: 8 }}>
                    {["SFx","SFy","SFz"].map(k => (
                      <label key={k} className={s.field}>
                        <span className={s.fieldLabel}>{k}</span>
                        <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} step="0.1" />
                      </label>
                    ))}
                  </div>
                )}
                {p.ScaleMethod === 2 && (
                  <div className={s.grid3} style={{ marginTop: 8 }}>
                    {[
                      { k: "SigmaFx", label: "σFx" },
                      { k: "SigmaFy", label: "σFy" },
                      { k: "SigmaFz", label: "σFz" },
                    ].map(({ k, label }) => (
                      <label key={k} className={s.field}>
                        <span className={s.fieldLabel}>{label} (m/s)</span>
                        <div className={s.inputRow}>
                          <input className={s.inp} type="number" value={p[k]} onChange={setNum(k)} step="0.1" />
                          <span className={s.unit}>m/s</span>
                        </div>
                      </label>
                    ))}
                  </div>
                )}

                {/* Mean wind profile */}
                <p className={s.sectionHead} style={{ marginTop: 14 }}>
                  Mean Wind Profile
                  <InfoPopover content={INFO.WindProfile} accentColor={ACCENT} />
                </p>
                <div className={s.grid2}>
                  <label className={s.field}>
                    <span className={s.fieldLabel}>
                      U ref <InfoPopover content={INFO.URef} accentColor={ACCENT} />
                    </span>
                    <div className={s.inputRow}>
                      <input className={s.inp} type="number" value={p.URef} onChange={setNum("URef")} step="0.5" />
                      <span className={s.unit}>m/s</span>
                    </div>
                  </label>
                  <label className={s.field}>
                    <span className={s.fieldLabel}>Profile type</span>
                    <select className={s.inp} value={p.WindProfile} onChange={setNum("WindProfile")}>
                      <option value={0}>0 — Constant</option>
                      <option value={1}>1 — Logarithmic</option>
                      <option value={2}>2 — Power law</option>
                    </select>
                  </label>
                  {p.WindProfile === 2 && (
                    <label className={s.field}>
                      <span className={s.fieldLabel}>PLExp_Hawc (α)</span>
                      <input className={s.inp} type="number" value={p.PLExp_Hawc} onChange={setNum("PLExp_Hawc")} step="0.01" />
                    </label>
                  )}
                  {p.WindProfile === 1 && (
                    <label className={s.field}>
                      <span className={s.fieldLabel}>
                        Z0 <InfoPopover content={INFO.Z0} accentColor={ACCENT} />
                      </span>
                      <div className={s.inputRow}>
                        <input className={s.inp} type="number" value={p.Z0} onChange={setNum("Z0")} step="0.001" />
                        <span className={s.unit}>m</span>
                      </div>
                    </label>
                  )}
                </div>
              </div>
            )}

            {/* ── User DLL params (type 6) ───────────────────────────────── */}
            {p.WindType === 6 && (
              <div className={s.sourceCard}>
                <div className={s.field}>
                  <span className={s.fieldLabel}>
                    <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      DLL wind file
                      <InfoPopover content={INFO.UserFile} accentColor={ACCENT} />
                    </span>
                  </span>
                  <div className={s.fileRow}>
                    <input className={s.inp} type="text"
                      value={p.UserFile === "none" ? "" : p.UserFile}
                      onChange={e => setP(prev => ({ ...prev, UserFile: e.target.value || "none" }))}
                      placeholder="Path to user-defined DLL…" />
                    <button className={s.browseBtn} onClick={browseUserFile} title="Browse" type="button">
                      <FolderOpen size={13} strokeWidth={1.8} />
                    </button>
                  </div>
                </div>
                <p className={s.hint} style={{ marginTop: 8 }}>
                  WindType=6 requires a DLL implementing the InflowWind user-defined wind interface.
                  Configure DLL-specific parameters directly in the .dat file.
                </p>
              </div>
            )}

            {/* Flow Direction */}
            <p className={s.sectionHead} style={{ marginTop: p.WindType === 1 ? 0 : 4 }}>
              Flow Direction
            </p>
            <div className={s.grid2}>
              <label className={s.field}>
                <span className={s.fieldLabel}><Lbl k="PropagationDir">Propagation direction</Lbl></span>
                <div className={s.inputRow}>
                  <input className={s.inp} type="number" value={p.PropagationDir} onChange={setNum("PropagationDir")} step="1" />
                  <span className={s.unit}>°</span>
                </div>
                <span className={s.hint}>Met. convention — 0° = wind from North</span>
              </label>
              <label className={s.field}>
                <span className={s.fieldLabel}><Lbl k="VFlowAng">Upflow angle</Lbl></span>
                <div className={s.inputRow}>
                  <input className={s.inp} type="number" value={p.VFlowAng} onChange={setNum("VFlowAng")} step="0.5" />
                  <span className={s.unit}>°</span>
                </div>
                <span className={s.hint}>Vertical flow inclination</span>
              </label>
            </div>

            {/* Velocity Output Point */}
            <p className={s.sectionHead}>Velocity Output Point</p>
            <div className={s.grid2}>
              <label className={s.field}>
                <span className={s.fieldLabel}><Lbl k="WindVziList">Hub height (Z)</Lbl></span>
                <div className={s.inputRow}>
                  <input className={s.inp} type="number" value={p.WindVziList} onChange={setNum("WindVziList")} />
                  <span className={s.unit}>m</span>
                </div>
                <span className={s.hint}>Match ElastoDyn HubHt</span>
              </label>
              <div className={s.field}>
                <span className={s.fieldLabel}><Lbl k="SumPrint">Summary file</Lbl></span>
                <Toggle
                  value={p.SumPrint}
                  onChange={v => setP(prev => ({ ...prev, SumPrint: v }))}
                  label="Write .IfW.sum"
                />
              </div>
            </div>

            {/* ── Create new file — only shown when no file is currently loaded ── */}
            {!filePath && (
              <>
                <p className={s.sectionHead}>Create file</p>
                <div className={s.outputRow}>
                  <div className={s.autoNameBox}>
                    <span className={s.autoNameLabel}>Auto-name</span>
                    <span className={s.autoNameVal}>{autoName}</span>
                  </div>
                  <label className={s.field} style={{ marginTop: 8 }}>
                    <span className={s.fieldLabel}>
                      Custom filename <span className={s.unit}>(optional override)</span>
                    </span>
                    <input
                      className={s.inp}
                      type="text"
                      value={customDatName}
                      placeholder={autoName}
                      onChange={e => setCustomDatName(e.target.value)}
                    />
                  </label>
                  {project && (
                    <span className={s.hint} style={{ marginTop: 4 }}>
                      → {project.modelDir ?? project.workingDir}/{effectiveDatName}
                    </span>
                  )}
                </div>
                <div className={s.actionRow}>
                  <button
                    className={s.writeBtn}
                    onClick={handleGenerate}
                    disabled={generating || !project}
                    title={!project ? "Select a project folder first" : undefined}
                    type="button"
                  >
                    {generating ? "Writing…" : `Generate ${effectiveDatName}`}
                  </button>
                </div>
              </>
            )}


          </div>
        </div>

        {/* ── Stats sidebar ──────────────────────────────────────────────── */}
        <div className={s.statsPanel}>
          <span className={s.statsLabel}>Quick stats</span>
          <div className={s.turbineWrap}>
            <WindVizSVG windType={p.WindType} windSpeed={p.HWindSpeed} plExp={p.PLexp} />
          </div>
          <div className={s.statsGrid}>
            {stats.map(({ k, v }) => (
              <div key={k} className={s.statCard}>
                <span className={s.statKey}>{k}</span>
                <span className={s.statVal}>{v}</span>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
